### ISSUE TITLE
Observables Import Fails

### ISSUE THREAD

**Issue by DR913** [OpenCTI-Platform/client-python#110]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

Importing any bundle that has Observables throws an error message `ERROR:root:An unexpected error occurred: { 'list' object has no attribute 'items' }`
I believe the error is because the `objects` list is being treated like a dictionary on [line 884 of opencti_stix2.py](https://github.com/OpenCTI-Platform/client-python/blob/9c5c1f4aa20f83229588b9510e261190fc5a2ebb/pycti/utils/opencti_stix2.py#L884)

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: OpenCTI 3.3.2
3. Other environment details: none

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Save the following test file for a Data import:
```
{
    "type": "bundle",
    "id": "bundle--10000000-0000-0000-0000-000000000001",
    "objects": [
        {
            "id": "observed-data--20000000-0000-0000-0000-000000000002",
            "type": "observed-data",
            "number_observed": 2,
            "objects": [
                {
                    "x_opencti_observable_type": "ipv4-addr",
                    "x_opencti_observable_value": "127.0.0.1",
                    "type": "ipv4-addr"
                },
                {
                    "x_opencti_observable_type": "ipv4-addr",
                    "x_opencti_observable_value": "127.0.0.2",
                    "type": "ipv4-addr"
                }
            ]
        }
    ]
}
```
2. Perform json Data import
3. Import will fail with error message: `{ 'list' object has no attribute 'items' }`

## Expected Output

Data would import successfully and populate Observables.

## Actual Output

Import will fail with error message: `{ 'list' object has no attribute 'items' }`
 
## Additional information

None

**Comment by SamuelHassine** [comment]
Hello,

This will be fully solved in the V4.

Kind regards,
Samuel
