### ISSUE TITLE
Unable to use the API

### ISSUE THREAD

**Issue by k-alki** [OpenCTI-Platform/client-python#136]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

Using the script create_indicator_of_campaign.py result with a failure.

## Environment

1. Ubuntu 20.04
2. Last OpenCTI version from the git
3. OpenCTI runs with docker

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. install opencti
2. create an user and change the token in the py
3. python3 create_indicator_of_campaign.py

## Expected Output

creation of a campaign with an indicator

## Actual Output

Only the campaign has been created

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Creating Campaign {My new Campaign}.
{'id': '7c2aa328-f2c3-4a8e-a21c-e7dc63d88038', 'standard_id': 'campaign--15e17dab-26c7-550d-b60d-d2cd004c5e7b', 'entity_type': 'Campaign', 'parent_types': ['Basic-Object', 'Stix-Object', 'Stix-Core-Object', 'Stix-Domain-Object'], 'createdById': None}
None
ERROR:root:[opencti_indicator] Missing parameters: name and pattern and main_observable_type
Traceback (most recent call last):
  File "/home/user/tmp/create_indicator_of_campaign.py", line 41, in <module>
    fromId=indicator["id"],
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

**Comment by azzarin** [comment]
Hi, i have the same issue with the example in the docu. 
I ll create a new issue aswell. but i get: 
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Reading Marking-Definition {marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da}.
ERROR:root:[opencti_indicator] Missing parameters: name and pattern and main_observable_type

**Comment by SamuelHassine** [comment]
Hello,

The example has been updated, `name`, `pattern` and `x_opencti_main_observable_type` are mandatory parameters to create an indicator.

Kind regards,
Samuel

**Comment by azzarin** [comment]
# Use the client to create an indicator in OpenCTI
indicator = opencti_api_client.indicator.create(
    name="C2 server of the new campaign",
    description="This is the C2 server of the campaign",
    pattern_type="stix",
    pattern="[ipv4-addr:value = '123.123.123.12']",
    main_observable_type="IPv4-Addr",
    valid_from=date,
    update=True,
    markingDefinitions=[TLP_GREEN_CTI["id"]],
    
    please advise ? but i belive i have name  in the parameters.

**Comment by k-alki** [comment]
thanks !

**Comment by azzarin** [comment]
I still get this error: 
AttributeError: 'OpenCTIApiClient' object has no attribute 'main_observable'
main_observable_type="IPv4-Addr",

**Comment by SamuelHassine** [comment]
Yes, it's `x_opencti_main_observable_type`, as I have written above and as the example now shows. The error message can be confusing it has been updated in 4.1.0.

**Comment by azzarin** [comment]
> Yes, it's `x_opencti_main_observable_type`, as I have written above and as the example now shows. The error message can be confusing it has been updated in 4.1.0.

Yeah i noticed. so i changed it to your examlpe:
observable = opencti_api_client.main_observable.create(
    
    name="C2 server of the new campaign",
    description="This is the C2 server of the campaign",
    pattern_type="stix",
    indicator_pattern="[domain-name:value = 'www.5z8.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']",
    
    pattern="[domain-name:value = 'www.5z8.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']",
    x_opencti_main_observable_type="IPv4-Addr",
    valid_from=date,
    
    
But i still get the error: 

 observable = opencti_api_client.main_observable.create(
AttributeError: 'OpenCTIApiClient' object has no attribute 'main_observable'

**Comment by SamuelHassine** [comment]
```
indicator = opencti_api_client.indicator.create(
    name="C2 server of the new campaign",
    description="This is the C2 server of the campaign",
    pattern_type="stix",
    pattern="[domain-name:value = 'www.5z8.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']",
    x_opencti_main_observable_type="IPv4-Addr",
    valid_from=date,
)
```

opencti_api_client.**indicator**.create

**Comment by azzarin** [comment]
> ```
> indicator = opencti_api_client.indicator.create(
>     name="C2 server of the new campaign",
>     description="This is the C2 server of the campaign",
>     pattern_type="stix",
>     pattern="[domain-name:value = 'www.5z8.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']",
>     x_opencti_main_observable_type="IPv4-Addr",
>     valid_from=date,
> )
> ```
> 
> The entity type is **indicator**: opencti_api_client.**indicator**.create

Sorry, that was just embarrassing from my side. Thanks for the quick reply and job. Works just fine.
