### ISSUE TITLE
Can't add marking definitions using stix_cyber_observable.add_marking_definition() function

### ISSUE THREAD

**Issue by daryakoval** [OpenCTI-Platform/client-python#140]
## Description

I am trying to add observable marking, using stix_cyber_observable.add_marking_definition() function, with the following arguments:     

mark_obj = MarkingDefinition(client)
marking_id = mark_obj.create(definition='TLP:GREEN', definition_type='TLP').get('id')
result = client.stix_cyber_observable.add_marking_definition(id=id, marking_definition_id=marking_id)

add_marking_definition function return an error because its trying to access non-existing key: "markingDefinitionsIds"
at this line: [here](https://github.com/OpenCTI-Platform/client-python/blob/master/pycti/entities/opencti_stix_cyber_observable.py#L1253)

Tried to debug this code, and when the code reaches this line: 
![image](https://user-images.githubusercontent.com/72339940/107878178-87c93080-6ed9-11eb-94aa-75ab0db9558c.png)
there is no key "markingDefinitionsIds" at stix_cyber_observable object, but there is "objectMarkingIds" key, maybe it is the requested key? 

## Environment

1. OS Mac OS 10
2. OpenCTI version: OpenCTI 4.0.7
3. Other environment details: python 3.8

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Try to use client.stix_cyber_observable.add_marking_definition function. 

## Expected Output

Adding new marking definition successfully.

## Actual Output
Error, because code is trying to access non-existing key: "markingDefinitionsIds".

**Comment by SamuelHassine** [comment]
Thanks for the issue! It will be fixed in the next release.
