### ISSUE TITLE
Failure to Create Location / Threat actor

### ISSUE THREAD

**Issue by mkulasi** [OpenCTI-Platform/client-python#141]
## Description
I get an error when i try to create Location / Threat Actor using API client

## Environment

1. Ubuntu
2. OpenCTI version: 4.0.3
3. Other environment details:

## Reproducible Steps

Steps to used to create location:
1. Query data from another OpenCTI system using pycti and run opencti_api_client.location.list(getAll=True) and i am getting all the results and process them
2. And try to create location from the initial OpenCTI system to my local station by using create method opencti_api_client.location.create(

name=eachdata['name'],
            type="Location",
            createdBy="kabwogi",
            objectMarking=eachdata['objectMarking'],
            objectLabel=eachdata['objectLabel'],
            externalReferences=eachdata['externalReferences'],
            stix_id=eachdata['id'],
            revoked=False,
            modified=eachdata['modified'],
            created=eachdata['created'],
            confidence=eachdata['confidence'],
            standard_id=eachdata['standard_id'],
            entity_type=eachdata['entity_type'],
            parent_types=eachdata['parent_types'],
            latitude=eachdata['latitude'],
            longitude=eachdata['longitude'],
            update=False,
            description=eachdata['description'],
            precision=eachdata['precision'],
            x_opencti_aliases=None
)
3.After executing the application i am getting below:

INFO:root:Reading Marking-Definition {marking-definition--34098fce-860f-48ae-8e50-ebd3cc5e41da}.
INFO:root:Listing Locations with filters null.
{'id': '43021a07-ffdc-4a99-9fbf-675999be709e', 'standard_id': 'location--0008f036-f7f3-597c-a209-572834eaa6c2', 'entity_type': 'City', 'parent_types': ['Basic-Object', 'Stix-Object', 'Stix-Core-Object', 'Stix-Domain-Object', 'Location'], 'spec_version': '2.1', 'created_at': '2021-02-03T15:58:58.983Z', 'updated_at': '2021-02-03T15:58:58.983Z', 'createdBy': None, 'objectMarking': [], 'objectLabel': [], 'externalReferences': [], 'revoked': False, 'confidence': 15, 'created': '2021-02-03T15:58:58.872Z', 'modified': '2021-02-03T15:58:58.872Z', 'name': 'Chemnitz', 'description': '', 'latitude': 50.8357, 'longitude': 12.9292, 'precision': None, 'x_opencti_aliases': None, 'createdById': None, 'objectMarkingIds': [], 'objectLabelIds': [], 'externalReferencesIds': []}
INFO:root:Creating Location {Chemnitz}.
INFO:root:{"errors":[{"message":"An unknown error has occurred","name":"UnknownError","time_thrown":"2021-02-17T21:46:40.231Z","data":{"reason":"No reason specify","category":"technical"}},{"message":"An unknown error has occurred","name":"UnknownError","time_thrown":"2021-02-17T21:46:40.231Z","data":{"reason":"No reason specify","category":"technical"}}]}

Traceback (most recent call last):
  File "D:/PERSONAL/MASTERS MATERIALS/notes masters/IA 614/OPENCTI-PROJECT/analyser.py", line 48, in <module>
    collect_data_from_openCTI()
  File "D:/PERSONAL/MASTERS MATERIALS/notes masters/IA 614/OPENCTI-PROJECT/analyser.py", line 23, in collect_data_from_openCTI
    indicator = opencti_api_client.location.create(
  File "D:\PYTHON\lib\site-packages\pycti\entities\opencti_location.py", line 254, in create
    result = self.opencti.query(
  File "D:\PYTHON\lib\site-packages\pycti\api\opencti_api_client.py", line 284, in query
    raise ValueError(r.text)
ValueError: {"errors":[{"message":"An unknown error has occurred","name":"UnknownError","time_thrown":"2021-02-17T21:46:40.231Z","data":{"reason":"No reason specify","category":"technical"}},{"message":"An unknown error has occurred","name":"UnknownError","time_thrown":"2021-02-17T21:46:40.231Z","data":{"reason":"No reason specify","category":"technical"}}]}

## Expected Output

I expected to get returned location object after creation

## Actual Output

what happen is an error message
 
## Additional information

Using the same approach i am to create indicators and update my local OpenCTI

**Comment by SamuelHassine** [comment]
Hello @mkulasi,

This should be solved in the latest version. Please re-open this issue if it's not the case.

Kind regards,
Samuel
