### ISSUE TITLE
api stix_core_relationship error query

### ISSUE THREAD

**Issue by jieyu-lin** [OpenCTI-Platform/client-python#143]
## Description

pycti package of version 4.2.3 has stix_core_relationship graphql query error.

## Environment

1. OS (where OpenCTI server runs): Windows 10
2. OpenCTI version: OpenCTI 4.2.3, pycti 4.2.3
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Python script: 
2. from pycti import OpenCTIApiClient
3. OpenCTIApiClient(url='xxx', token='yyy').stix_core_relationship.list()

## Expected Output

It should be a list of relationships

## Actual Output

ValueError: {"errors":[{"message":"Unknown argument \"elementId\" on field \"Query.stixCoreRelationships\".","locations":[{"line":3,"column":43}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}
 
## Additional information

delete graphql query "elementId" in stix_core_relationship list query will fix

**Comment by SamuelHassine** [comment]
Hello,

This should now be solved in the latest version. Please re-open this issue if it's not the case!

Kind regards,
Samuel
