### ISSUE TITLE
Cant import text observables from pycti

### ISSUE THREAD

**Issue by Alfon-sec** [OpenCTI-Platform/client-python#148]
## Description
Small variable name mistake that makes imposible to create an observable type text via pycti

## Reproducible Steps
execute a script to append an observable type text to the API via pycti

## Expected Output
Creating Stix-Cyber-Observable {X-OpenCTI-Text} with indicator at True.

## Actual Output

ValueError: {'name': 'FunctionalError', 'message': 'Observable type X-OpenCTI-text is not supported.'}
 
## Additional information

The problem is in:
 File  the file -> pycti/entities/opencti_stix_cyber_observable.py
 on line 474
'''
 elif type.lower() == "x-opencti-text":
            type = "X-OpenCTI-text"
'''
SOLUTION:
type = "X-OpenCTI-Text"

**Comment by SamuelHassine** [comment]
Thanks a lot !

**Comment by SyeedHasan** [comment]
@SamuelHassine This still doesn't work I believe.

**Comment by SyeedHasan** [comment]
> ValueError: {'name': 'FunctionalError', 'message': 'Observable type X-OpenCTI-Text is not supported.'}
Can't seem to create Text observables with the type, X-OpenCTI-Text, Text, or any other variant. 

Any solution around this?

**Comment by SamuelHassine** [comment]
Please use 

```test = opencti_api_client.stix_cyber_observable.create(observableData={"type": "x-opencti-text", "value": "test"})```
