### ISSUE TITLE
Port examples to tests

### ISSUE THREAD

**Issue by rhaist** [OpenCTI-Platform/client-python#150]
With the new pytest framework in the codebase we can migrate all existing examples to tests.
User will still be able to look up how some of the library functions can be used but they also increase our test coverage this way.

Win Win :)

**Comment by nor3th** [comment]
I don't think that we have to migrate them. What we could do instead is to load them into the test runs. 
To make them "loadable" I think it is necessary to put the examples at least into a function and use a layout like this:

1. prepare a use case
2. do/show something
3. return the accomplished changes

Using the returned values from the examples in the test would only require to validate the results against an expected result.

This approach can then be used for unit tests as well as integration tests using CircleCi. Any thoughts?

**Comment by nor3th** [comment]
Hey

I wrote a couple of unit tests for the utils functions and a few CRUD integration tests for the entities (#192 ). My focus is to test the behavior of the interfaces which are accessed in production that they work as they should, hence I won't bother too much with more unit tests. I will continue to write a few tests for the connector class and then leave the pycti tests for now. 

My idea is that those tests are continuously extended/improved when there are new externally reachable features introduced or bugs are fixed.  

@SamuelHassine  is it possible to implement a new guideline for pycti which requires tests to be written for new PRs (for new/changed externally reachable features or fixed bugs)?

Thanks

**Comment by SamuelHassine** [comment]
Considering the current test suit as enough for the moment.
