### ISSUE TITLE
Is API version 4.2.4 backward compatible?

### ISSUE THREAD

**Issue by timebotdon** [OpenCTI-Platform/client-python#151]
I'd like to first of say big thank you for the astounding development progress! Loving that this product has grown alot over the last few months.

Anyway I need to clarify if API version 4.2.4 is backward compatible? I'm currently using API v4.0.7 for connector development, and am intending to upgrade my OpenCTI platform instance to v4.2.4. Do I need to upgrade the python API as well?

Thank you!

**Comment by SamuelHassine** [comment]
Hello @timebotdon,

You should align Python client version and platform version. We do not take care about backward compatibility of new Python client release.

Kind regards,
Samuel

**Comment by timebotdon** [comment]
Thanks for the clarification! 😁
