### ISSUE TITLE
Upload a file from a connector

### ISSUE THREAD

**Issue by Darkheir** [OpenCTI-Platform/client-python#152]
## Problem to Solve

Upload a file from a connector using `OpenCTIConnectorHelper` `send_stix2_bundle` method.

## Current Workaround

Right now there is no easy way to do it except calling `OpenCTIStix2` `import_object` method with the attribute `x_opencti_files` set in the object.
It is executed synchronously so this is not optimal when creating hundreds or thousands of objects with files. 

There is also the relationships and references matter that needs to be handled.

## Proposed Solution

It would be much better if we could have this `x_opencti_files` in the bundle's objects so it can be processed asynchronously by the worker.

## Additional Information

Right now `OpenCTIStix2` `import_object` is calling

```python
self.opencti.stix_domain_object.add_file(
    id=stix_object_result["id"],
    file_name=file["name"],
    data=base64.b64decode(file["data"]),
    mime_type=file["mime_type"],
)
```

Meaning that `file["data"]` is a base64 encoded bytes string. 

If we want to keep the same format then `data` will need to be a string and not a bytes string because the bundle sent to the worker is json encoded.

**Comment by SamuelHassine** [comment]
Hello @Darkheir,

I'm glad to say that `x_opencti_files` is already implemented (and used in the [CrowdStrike connector](https://github.com/OpenCTI-Platform/connectors/blob/c6cc81af3e251675fbe25be76fdd5282709e8ee3/crowdstrike/src/crowdstrike/utils/__init__.py#L829)).

Specifications are:

```
x_opencti_files=[{"name":"Name of the file", "data": base64_encode(file data), "mime_type": "File MIME type"}]
```

Kind regards,
Samuel

**Comment by Darkheir** [comment]
Hi @SamuelHassine 

Thank you for the answer, that's awesome !

I didn't find any documentation about this feature, so I opened an issue but it works great for me :-)
