### ISSUE TITLE
Location objects in reports are not imported

### ISSUE THREAD

**Issue by VVX7** [OpenCTI-Platform/client-python#154]
## Description

When importing a exported report, location entities are not imported.

## Environment

1. OS: Ubuntu 20.04
2. OpenCTI version: 4.3.0
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import location entities via opencti geography connector.
2. Create a report with Location entities and export it as JSON via the frontend.
3. Import the JSON file via frontend.
4. Browse to report knowledge graph and see that location entities are not present.

## Expected Output

Locations should be imported.

## Actual Output

Locations are not imported. :(
 
## Additional information
```
worker2_1                                | INFO:root:Adding StixObjectOrStixRelationship {location--2f77493c-e361-52a2-bd2e-72a5d1f0a3e9} to Report {7e3b8905-7c13-4872-a94e-a48b65a04505}
worker2_1                                | ERROR:root:Expect only one response
worker2_1                                | ERROR:root:Missing reference location--2f77493c-e361-52a2-bd2e-72a5d1f0a3e9
worker2_1                                | INFO:root:Adding StixObjectOrStixRelationship {location--a3d966ac-b0e3-5b6f-ac88-c608779aef41} to Report {7e3b8905-7c13-4872-a94e-a48b65a04505}
worker2_1                                | ERROR:root:Expect only one response
worker2_1                                | ERROR:root:Missing reference location--a3d966ac-b0e3-5b6f-ac88-c608779aef41
```

**Comment by SamuelHassine** [comment]
@richard-julien @VVX7 This bug will be resolved in the next release. However, old imports will not work if they contain location entities.
