### ISSUE TITLE
Is possible to query attack-pattern by external reference?

### ISSUE THREAD

**Issue by Songchunbo** [OpenCTI-Platform/client-python#159]
## Question

I don't found any API from 'pycti' to query attack-pattern by external reference id.  Also tried below query , it didn't work.  Is possible to query attack-pattern by external reference?

```
query {
  attackPatterns(search:"T1111") {            // Here T1111 is a customized external id.
    edges {
      node {
        id
        x_mitre_id
        x_opencti_stix_ids
        externalReferences {
          edges {
            node {
              id
              external_id
              source_name
              url
            }
          }
        }
      }
    }
  }
}
```

**Comment by nor3th** [comment]
Good question, but unfortunately it is not yet possible. 
There is the x_mitre_id which works for MITRE IDs, but for example for CAPE this approach doesn't work. 

```
opencti_api_client.attack_pattern.read(
    filters={'key': 'x_mitre_id', 'values': ['T1111']}
)
```

Adding this feature requires a few tweaks also on the OpenCTI side.
The filterable fields for Attack Pattern are listed here: 
https://github.com/OpenCTI-Platform/opencti/blob/9c3390badc8e5118e145e55478dc1070e04b30ec/opencti-platform/opencti-graphql/src/schema/stixDomainObject.js#L200-L224

@SamuelHassine can you make a feature request out of this issue?

**Comment by nor3th** [comment]
Closed due inactivity.
