### ISSUE TITLE
Possible race condition when creating non-existing objects?

### ISSUE THREAD

**Issue by jekyc** [OpenCTI-Platform/client-python#18]
## Description
During import of the opencti dataset (https://github.com/OpenCTI-Platform/datasets/blob/master/data/sectors.json), identities can be created more than once when multiple workers are used. 

I think this exact issue is related to the method `split_stix2_bundle` in https://github.com/OpenCTI-Platform/client-python/blob/1.2.15/pycti/opencti_connector_helper.py, as this creates a bundle per SDO or SRO. The pseudo bundles below illustrate (condensed to only include the relevant object IDs) two bundles created by the `split_stix2_bundle`. 

```
Bundle A: {
    relationship--d4a1c31b-3bdd-458a-ac01-614e0ab871e2,
    identity--7083bf6a-87f7-40a7-b888-a919312f82e5,
}

Bundle B: {
    relationship--4708ce1b-1960-4c67-a408-dc6f26db325d
    identity--7083bf6a-87f7-40a7-b888-a919312f82e5,
}
```
Note, that because the Identity 7083bf6a-87f7-40a7-b888-a919312f82e5 has multiple relations, it is included in both the bundles, which in and of itself is not a problem, but if the bundles are processed by different workers at the same time, each worker will insert a copy of the Identity with different database/grakn IDs but with the same STIX ID, since the Identiry does not exist yet.

I don't think `split_stix2_bundle` is directly responsible for this behavior, but it does help highlight a (general?) race condition issue during (parallel?) imports.

I don't know enough about the internal workings of the Elasticsearch and grakn queries used in opencti to have a solution, but Elasticsearch is only Near Real Time, so this might be an issue? If it is, the `refresh` parameter might be helpful (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html).

Would it help to use the STIX Object ID as the primary/document ID help here, as the second document creation would/should fail since a document with that ID already exists?

Another solution could be to ensure that objects with no relationships are created first (and are querable), before inserting other objects that depend on them. While this would fix the current problem I'm not sure if it would be a viable long-term solution.

## Environment

1. OS (where OpenCTI server runs): Docker containers in swarm mode
2. OpenCTI version: latest docker image
3. Elasticsearch and Grakn are on different machines

## Reproducible Steps
Steps to create the smallest reproducible scenario:
1.  Setup
1.1. Clean all databases (ES and grakn)
1.2. Ensure that the opencti-connector is included as a service import worker as more than one replica.
2.  Run docker-compose --compatibility up 

## Expected Output
Only one copy of each sector (such as "Culture and entertainment") should be created.

## Actual Output
Multiple copies of the same sector are (sometimes) created.

## Additional information

**Comment by richard-julien** [comment]
Hi @jekyc thanks for the report.
We try to be fast as possible to inject the data by splitting the stix2 object in chunks. The chunks are created to be consistent so sometimes we duplicate information and like you said, we can have race conditions when using multiple workers to inject the data.
In the case of 2 creations on the same time I think we need to modify the Grakn schema to use the **key** word on stix2_id. It will act as an id and so the creation will be rejected in Grakn. The transaction will be rejected and so retry with success right after. If I remember will this word was not available (or not working) in grakn at project start.

**Comment by richard-julien** [comment]
Find it https://github.com/graknlabs/grakn/pull/4995.
