### ISSUE TITLE
Uploading files to OPENCTI as artifact #question

### ISSUE THREAD

**Issue by romarusestsky** [OpenCTI-Platform/client-python#187]
I want to create artifacts with downloadable files via API.
But I can't get it to work.
![image](https://user-images.githubusercontent.com/28838722/120612425-de915080-c45d-11eb-86bf-3d0becac354c.png)

![image](https://user-images.githubusercontent.com/28838722/120612372-cc171700-c45d-11eb-8866-e05e8592a21f.png)

"""
file = r"file path on disk"

data = None
with open(file, 'rb') as r_h:
    data = r_h.read()

md5 = hashlib.md5()
sha1 = hashlib.sha1()
sha256 = hashlib.sha256()
md5.update(data)
sha1.update(data)
sha256.update(data)
md5 = md5.hexdigest()
sha1 = sha1.hexdigest()
sha256= sha256.hexdigest()    

artifact = opencti_api_client.stix_cyber_observable.create(
    type='Artifact',
    update=True,
    createIndicator=True,
    x_opencti_additional_names=sha256,
    observableData={
        "type": "Artifact",
        "mime_type": "application/octet-stream",
        "x_opencti_additional_names": sha256,
        "hashes": {
            "sha-1": sha1,
            "sha-256": sha256,
            "md5": md5,
        },
        "x_opencti_score": 100,
        "payload_bin": base64.b64encode(data)
    }
)
"""

I can't get it to actually upload the file.

**Comment by SamuelHassine** [comment]
Done. Example is here: https://github.com/OpenCTI-Platform/client-python/blob/master/examples/upload_artifact.py.
