### ISSUE TITLE
[StixCyberObservable] Can not create new observables

### ISSUE THREAD

**Issue by nor3th** [OpenCTI-Platform/client-python#188]
## Description

Using the StixCyberObservable to create new observables fails and doesn't create a new observable.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 4.5.4
3. Other environment details: pycti is also 4.5.4

## Reproducible Steps

```
opencti_api_client = OpenCTIApiClient(api_url, api_token)
observable = opencti_api_client.stix_cyber_observable.create(
    type="IPv4-Addr", observable_value="123.45.78.90"
)
print(observable)
```
->
```
$ python3 test.py
INFO:root:Listing Threat-Actors with filters null.
None
```

## Expected Output

A newly created IPv4 observable and a python dict with the specifics from pycti

## Actual Output

No new observable has been created. No relevant logs entries in the OpenCTI logs.

## Other info

Creating new observables using the observableData approach works however.

```
opencti_api_client = OpenCTIApiClient(api_url, api_token)
observable = opencti_api_client.stix_cyber_observable.create(
    observableData={
        "type": "file",
        "hashes": {
            "md5": "16b3f663d0f0371a4706642c6ac04e42",
            "sha1": "3a1f908941311fc357051b5c35fd2a4e0c834e37",
            "sha256": "bcc70a49fab005b4cdbe0cbd87863ec622c6b2c656987d201adbb0e05ec03e56",
        },
    }
)
print(observable)
```
->
```
$ python3 test2.py
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Creating Stix-Cyber-Observable {StixFile} with indicator at False.
{'id': 'f2d9e636-fabd-45ec-a412-716fbb6e89cd', 'standard_id': 'file--9b8836e6-1297-5734-aace-42ee12895e5e', 'entity_type': 'StixFile', 'parent_types': ['Basic-Object', 'Stix-Object', 'Stix-Core-Object', 'Stix-Cyber-Observable'], 'indicators': [], 'createdById': None, 'indicatorsIds': []}
```

**Comment by richard-julien** [comment]
Are you able to reproduce in 4.5.5 ?

**Comment by nor3th** [comment]
Yes, but I just noticed why the issue is caused...

The code was taken from one of the examples. Here a code snippet:
https://github.com/OpenCTI-Platform/client-python/blob/27a8d4fcbc6b4b149d2eedbc013abdfda8958e7f/examples/create_incident_with_ttps_and_indicators.py#L58-L60

Yet it seems that StixCyberObservable was changed and doesn't incorporate the arguments `type` and `observable_value` anymore.
https://github.com/OpenCTI-Platform/client-python/blob/27a8d4fcbc6b4b149d2eedbc013abdfda8958e7f/pycti/entities/opencti_stix_cyber_observable.py#L438-L458

Hence with code from the examples, the create functions finishes here
https://github.com/OpenCTI-Platform/client-python/blob/27a8d4fcbc6b4b149d2eedbc013abdfda8958e7f/pycti/entities/opencti_stix_cyber_observable.py#L469-L470

Using the updated function arguments, everything works as intended:
```
observable = opencti_api_client.stix_cyber_observable.create(
    simple_observable_key="IPv4-Addr.value", simple_observable_value="123.45.78.90", createIndicator=True
)
print(observable)
```
-->
```
$ python3 test.py
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Creating Stix-Cyber-Observable {IPv4-Addr} with indicator at True.
{'id': '93fad6e0-3d29-49f5-8dde-ecd6c1bc3ccf', 'standard_id': 'ipv4-addr--4e058877-9ab2-543f-8502-1aae95a41476', 'entity_type': 'IPv4-Addr', 'parent_types': ['Basic-Object', 'Stix-Object', 'Stix-Core-Object', 'Stix-Cyber-Observable'], 'indicators': [{'id': '4e42621d-88ce-4ecd-9178-9e9dbfa5ee99', 'pattern': "[ipv4-addr:value = '123.45.78.90']", 'pattern_type': 'stix', 'createdById': None}], 'createdById': None, 'indicatorsIds': ['4e42621d-88ce-4ecd-9178-9e9dbfa5ee99']}
```

I will update the examples with the 'new' function arguments then. I'll close this for now.
