### ISSUE TITLE
[FEATURE] Add Ability to Que Enrichment of an object

### ISSUE THREAD

**Issue by mwatermolen** [OpenCTI-Platform/client-python#193]
## Problem to Solve

From the python client add the ability to request enrichment of an object by ID

## Current Workaround

Using the GraphQL API

## Proposed Solution

Implement a class for calling enrichment 

Thanks in advance!

**Comment by nor3th** [comment]
Hmm that shouldn't be too difficult to implement in the SDO class with a given ID. What's the graphql query you currently use to launch enrichments?

**Comment by mwatermolen** [comment]
Hello @nor3th, I have not built the query yet, Just validated that its possible w/ Julian

**Comment by mwatermolen** [comment]
Hey @nor3th, 

Sorry for the delay, here is the payload sent to graphQL on enrichment

```json
{
    "stixCoreObjectEdit": {
        "askEnrichment": {
            "id": "opencti-work--dcecd212-ed7b-4dd2-93f8-4d18d07e8ad9"
        }
    }
}
```

**Comment by nor3th** [comment]
Awesome, thanks for that. Seems like the main logic seems to be here. https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/src/domain/enrichment.js
