### ISSUE TITLE
[BUG][x509] x509 Serial Number wont take string w/o delimiter 

### ISSUE THREAD

**Issue by mwatermolen** [OpenCTI-Platform/client-python#195]
## Description

Howdy all, Working on x509 import and want sure if I was doing something wrong or if this is a bug. But it seems that the x509 wont take a value for version or serial as a str or int (same error below)

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: { e.g. OpenCTI 1.0.2 }
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. call self.helper.api.stix_cyber_observable.create() with data below

***Observable data:***
```
observableData: {
    hashes: {
        sha1: 'ea81cd3f69de666cf5b9a9beda48d54d8e01053c', 
        sha256: '8be5e3369280b3203d109775afb05c48ecb120ec9aa0ff998935ed66f4bfa895'
    }, 
    issuer: 'CN=vmi475662', 
    serial_number: '163141214286181385384565430465499332298', 
    signature_algorithm: 'sha256WithRSAEncryption', 
    subject: 'CN=vmi475662', 
    subject_public_key_algorithm: 'rsa', 
    type: 'x509-certificate', 
    validity_not_after: '2021-10-14T11:25:22', 
    validity_not_before: '2021-04-14T11:25:22'
}, 
```

## Expected Output

Takes serial as a string w/o needing to be delimited by `:` every 2 chars ex `11:34:23:15:35:21:75:08:08:34:57:59:44:09:94:83:80:00:09:3`

## Actual Output

ERROR:
```{'name': 'Variable "$X509Certificate" got invalid value 1.6314121428618138e+38 at "X509Certificate.serial_number"; String cannot represent a non string value: 1.6314121428618138e+38', 'message': 'Variable "$X509Certificate" got invalid value 1.6314121428618138e+38 at "X509Certificate.serial_number"; String cannot represent a non string value: 1.6314121428618138e+38'}```
 
## Additional information

```python
    def _generate_x509(self, shodanHostResponse):
        x509s = []

        for service in shodanHostResponse["data"]:
            if "ssl" in service:
                sslObject = service["ssl"]

                issued: datetime = datetime.strptime(
                    sslObject["cert"]["issued"], "%Y%m%d%H%M%SZ"
                )
                expires: datetime = datetime.strptime(
                    sslObject["cert"]["expires"], "%Y%m%d%H%M%SZ"
                )

                x509 = self.helper.api.stix_cyber_observable.create(
                    observableData={
                        "type": "x509-certificate",
                        "issuer": " ".join(
                            (
                                f"{k}={v}"
                                for k, v in sslObject["cert"]["subject"].items()
                            )
                        ),
                        "validity_not_before": issued.isoformat(),
                        "validity_not_after": expires.isoformat(),
                        "subject": " ".join(
                            (f"{k}={v}" for k, v in sslObject["cert"]["issuer"].items())
                        ),
                        "serial_number": str(sslObject["cert"]["serial"]),
                        "version": str(sslObject["cert"]["version"]),
                        "hashes": {
                            "sha256": sslObject["cert"]["fingerprint"]["sha256"],
                            "sha1": sslObject["cert"]["fingerprint"]["sha1"],
                        },
                        "signature_algorithm": sslObject["cert"]["sig_alg"],
                        "subject_public_key_algorithm": sslObject["cert"]["pubkey"]["type"],
                    },
                    update=True,
                )
                x509s.append(x509)
        return x509s
```

**Comment by nor3th** [comment]
Hey @mwatermolen 

`version` as well as `serial` are both defined as String values in the GraphQL DB schema with which it is possible to save those objects.
https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/config/schema/opencti.graphql#L6073-L6074

As the error log said, you are just not allowed to define those two attributes as an integer value, but as long as the values are a string value `11:34:23:15:35:21:75:08:08:34:57:59:44:09:94:83:80:00:09:31` as well as '163141214286181385384565430465499332298' are possible. 

I am not sure if it's a great idea to allow the second option to be stored in OpenCTI as well...

![screen4](https://user-images.githubusercontent.com/73965465/132092043-61ba54d9-cc11-4cb4-9ebb-5fdbc4954f56.png)
![screen3](https://user-images.githubusercontent.com/73965465/132092044-7ad5dcea-0b2f-41bf-bd78-d1c7b94a7900.png)

Regards,

**Comment by nor3th** [comment]
Closed due to inactivity
