### ISSUE TITLE
requirements too strict for external integrations

### ISSUE THREAD

**Issue by mlodic** [OpenCTI-Platform/client-python#200]
Hi everyone, I am the author of IntelOwl and we are working on integrating OpenCTI to IntelOwl. See [PR](https://github.com/intelowlproject/IntelOwl/pull/602)

I would kindly ask you to soften the requirements of this library. For most of the required packages there is no need to set a specific version without supporting any other one. This would complicate every kind of external integrations, like the one of us.

In particular, because of the `requests==2.25.1` requirement, we would need to downgrade that package ([2.26.0 now](https://pypi.org/project/requests/)) to use the pycti library.

So please at least set `requests>=2.25` or, even better, `requests~=2.26` and release a new version of the library.

Thank you in advance

**Comment by mlodic** [comment]
any update on this? @SamuelHassine

**Comment by mlodic** [comment]
hi... I don't know why you reverted this but the problem persists in the new version of the library....
can you please just keep this requirement: `requests~=2.26`. Otherwise it is impossible to use this library.

Thank you

**Comment by nor3th** [comment]
Hey @mlodic 

Sorry about that, just fixed it for the 5.1.2 version. Just pull the newest update.

Regards

**Comment by mlodic** [comment]
thank you @nor3th, really appreciated. When we have the version fixed on pypi we will update the package

**Comment by nor3th** [comment]
Hey @mlodic 

I just released the `5.1.2a0` version, please use this one as it resolves this issue while keeping all 5.1.2 features. 
https://pypi.org/project/pycti/5.1.2a0/

Regards
