### ISSUE TITLE
Cannot create ip to as relationship using API

### ISSUE THREAD

**Issue by dinatep** [OpenCTI-Platform/client-python#205]
## Description
This relationship type is specified in the STIX specification and offered by the UI when creating a relationship between the two, but trying to create such a relationship raises an error.

## Environment
OS (where OpenCTI server runs): Alpine Linux
OpenCTI version:4.5.5
OpenCTI client:4.5.5

## Reproducible Steps
Steps to create the smallest reproducible scenario:

`cti.stix_core_relationship.create(fromId=<ip-id>, toId=<as-id>, relationship_type='belongs-to')`

## Expected Output
A new relationship of type belongs-to to be created between the two

## Actual Output
`ValueError: {'name': 'FunctionalError', 'message': 'The relationship type belongs-to is not allowed between IPv4-Addr and Autonomous-System'}`

## Additional information

**Comment by nor3th** [comment]
Hey @dinatep 

This issue has been resolved in the current development version. Try using either the `rolling` or the `5.0.0` (under development) version. There it will work.
https://github.com/OpenCTI-Platform/opencti/issues/1425

```
ip = api_client.stix_cyber_observable.create(
    observableData={
        "type": "ipv4-addr",
        "value": "8.8.8.8",
    }
)
asn = api_client.stix_cyber_observable.create(
    observableData={
        "type": "Autonomous-System",
        "number": 1234,
    }
)
rel = api_client.stix_core_relationship.create(fromId=ip['id'], toId=asn['id'], relationship_type='belongs-to')
print(rel)
```
```
$ python test.py 
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Creating Stix-Cyber-Observable {IPv4-Addr} with indicator at False.
INFO:root:Creating Stix-Cyber-Observable {Autonomous-System} with indicator at False.
INFO:root:Creating stix_core_relationship {d74ae457-6b32-496a-974a-978f9852a606, cb6a1008-de8b-4e4c-9d46-4324f24a3abd}.
{'id': 'a6ada279-9b35-4b53-adc3-e25401001475', 'standard_id': 'relationship--8da99c23-1e1f-41f4-8423-fb2d603eaf49', 'entity_type': 'belongs-to', 'parent_types': ['basic-relationship', 'stix-relationship', 'stix-core-relationship'], 'createdById': None}
```

Regards

**Comment by nor3th** [comment]
Closed due to inactivity
