### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by b4dpxl** [OpenCTI-Platform/client-python#21]
## Description

Firstly, it's possible I'm using the client wrong. I'm creating a connector to import reports, and trying to link entities as knowledge, specifically intrusion-sets, countries, and sectors. I've noticed that these seem to be case sensitive, sometimes resulting in new entities being created. Originally I was just creating a stix bundle and uploading it, so I tried using the client `search_stix_domain_entities_by_name` method to find the existing id and use that. The feed I'm using has some inconsistencies, particularly in the case of items (plus random pluralisation).

## Environment

1. OS (where OpenCTI server runs): Ubuntu
2. OpenCTI version: OpenCTI 1.1.2
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. client.search_stix_domain_entities_by_name("Cobalt Group")
2. client.search_stix_domain_entities_by_name("Cobalt group")

## Expected Output
Both should return matches

## Actual Output

Only `1` returns a match.

**Comment by b4dpxl** [comment]
More information. This is the test I ran:

`client = opencti_api_client.OpenCTIApiClient(url, token)

name="Cobalt Group"
print(f"Checking for {name}")
results = client.search_stix_domain_entities_by_name(name)
print(results)
print("Got {} results".format(len(results)))

print()
name="cobalt group"
print(f"Checking for {name}")
results = client.search_stix_domain_entities_by_name(name)
print(results)
print("Got {} results".format(len(results)))
`

![image](https://user-images.githubusercontent.com/26406101/64907972-b6921480-d6f1-11e9-8792-c4c9b0e31277.png)

**Comment by SamuelHassine** [comment]
The methods are case insensitive, this is a problem from ElasticSearch, the 2.0.0 release will solve the problem.
