### ISSUE TITLE
[STIX IMPORT] - Relation create fromId and toId not exists with x_opencti_source_ref 

### ISSUE THREAD

**Issue by hieuit7** [OpenCTI-Platform/client-python#220]
## Description
I use taxii collection from Internal Opencti (call is A instance )to export data to other Instances (call B instance).
But, all Input Object from GraphQL API A can't create with x_opencti_id fields to import into B.

What is your mean with x_opencti_source_ref is priority higher source_ref in this case? 
 
![image](https://user-images.githubusercontent.com/6295584/138581346-2d8f1bfc-0557-4a15-97cd-6ff8354bbd7d.png)

## Environment

1. OS: Docker Kubernetes
2. OpenCTI version: >=4.0.5 
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. From A, create A Taxii Collection 
2. From B use connector and worker to import.

## Expected Output

StixCoreRelationShip is imported

## Actual Output

 StixCoreRelationShip can't import
 
## Additional information

In my opinion, this action can be remove check x_opencti

**Comment by SamuelHassine** [comment]
Hello @hieuit7,

Thanks for opening this issue. You're absolutely, it will be remove in the next release.

Kind regards,
Samuel
