### ISSUE TITLE
stix_cyber_observable_relationship.list() doesn't work

### ISSUE THREAD

**Issue by dinateper** [OpenCTI-Platform/client-python#223]
## Description

stix_cyber_observable_relationship.list() produces an error for the $relationship_type field

## Environment

1. OS (where OpenCTI server runs): Alpine
2. OpenCTI version: 5.0.3
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. run cti.stix_cyber_observable_relationship.list(elementId='some_id')
2. error

## Expected Output

list of relevant relationships

## Actual Output

![image](https://user-images.githubusercontent.com/79656950/141990888-609c1408-e1fc-4318-b03a-8fec5ae3d747.png)

**Comment by SamuelHassine** [comment]
@dinateper @nor3th thanks and indeed the GraphQL query was not correct. But our generic function to list relationships now support list of relationship types. I will rollback this PR and change the GraphQL schema to support list of strings.

It still possible to just pass a simple string, GraphQL will automatically wrap it in a list.
