### ISSUE TITLE
Cannot create `StixCyberObservableRelationship` with `NetworkTraffic` via pycti API.

### ISSUE THREAD

**Issue by eliataylor** [OpenCTI-Platform/client-python#231]
## Description

Get `FunctionalError` when creating a `StixCyberObservableRelationship` between any two observable types with or without a valid "relationship_type" using `pycti`

However, I _can_ create relationships using the OpenCTI interface. The screenshot below shows me reading that valid relationship, in order to to verify the "src" is an appropriate type for this type of relationship.

I'm calling:
`
self.api.stix_cyber_observable_relationship.create(fromId= ip["id"], toId= networkTraffic["id"], relationship_type= "src")
`

and get this error
`{'name': 'FunctionalError', 'message': 'The relationship type src is not allowed between IPv4-Addr and Network-Traffic'}`

<img width="1386" alt="Screen Shot 2021-12-18 at 11 41 29 AM" src="https://user-images.githubusercontent.com/6335974/146665790-b9e98a6f-58be-41a5-846e-f991407ff1fb.png">

## Environment

1. OS: MacOS 11.16.1
2. OpenCTI version: I've tried 5.0.0 and 5.1.2
3. Other environment details: Using Docker for OpenCTI Platform/Workers

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Follow this [example](https://github.com/OpenCTI-Platform/client-python/blob/e014f06dc79db15baef5ea91058a911d17391651/examples/create_ip_domain_resolution.py) to create a NetworkTraffic and IP observed_data. Related them with `opencti_api_client.stix_cyber_observable_relationship.create` using any relationship_type or "dst" or "src"
2. run
3. watch it fail.

## Expected Output
Creates a valid `StixCyberObservableRelationship`

## Actual Output
Error above.

## Additional Information:
https://github.com/OpenCTI-Platform/client-python/issues/205 might be related but this is a `stix_core_relationship` vs. a `stix_cyber_observable_relationship`

**Comment by nor3th** [comment]
Hey @eliataylor 

According to the STIX 2.1 definition, there is no IPv4 --src--> NetworkTraffic relationship (https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_exv6owtle2d1) . There's only the NetworkTraffic's attribute `src-ref`(https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_e5nyr5squmsd) which is allowed to establish a reference to IPv4,IPv6,MAC and a Domain Name.

Try setting the `src-ref` attribute of NetworkTraffic and please let me know if it worked.

Regards

**Comment by eliataylor** [comment]
@nor3th, unfortunately that did not work, nor do any of the reference properties. I created an Issue here: https://github.com/OpenCTI-Platform/opencti/issues/1785

I'm far from a GraphQL expert and this is a bit of a side project for me, but if I added the properties the `input NetworkTrafficAddInput` is that enough? Or would I need to edit the mutation / query?

**Comment by nor3th** [comment]
Hey @eliataylor 

I just noticed the issue which your query didn't work. You tried to to create a relationship as `IPv4 -src-> NetworkTraffic` which is the wrong way around. Give this a try
```
self.api.stix_cyber_observable_relationship.create(fromId= networkTraffic["id"], toId= ip["id"], relationship_type= "src"
```

Regards

**Comment by eliataylor** [comment]
Could have sworn I tried both directions and various verb formats for the relationship_type. 

But this works now. Closing
