### ISSUE TITLE
Internal server error when trying to run get_all_indicators_using_pagination.py

### ISSUE THREAD

**Issue by Palastia** [OpenCTI-Platform/client-python#232]
## Description
Greetings, I am trying to run one of the scripts in the examples but it doesn't seem to work for me. The script get_all_reports_using_pagination.py however, seems to run without errors. Any advise or help is appreciated. Thank you.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 16.4
2. OpenCTI version: OpenCTI 5.0.2
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Replace opencti url and api token placeholders in script
2. Run script
3. Error appears

## Expected Output
The script runs successfully and a list of indicators are shown in output.

## Actual Output
INFO:root:Listing Indicators with filters null.
ERROR:root:Internal server error
Traceback (most recent call last):
   File "get_all_indicators_using_pagination.py", line 25, in <module>
      data = opencti_api_client.indicator.list(
   File "usr/local/lib/python3.8/dist-packages/pycti/entities/opencti_indicator.py, line 217, in list
      result = self.opencti.query(
   File "usr/local/lib/python3.8/dist-packages/pycti/api/opencti_api_client.py", line 314 in query
      raise ValueError(
ValueError: {'name': 'Internal server error', 'message': 'Internal server error'}

**Comment by nor3th** [comment]
Hey @Palastia 

`Internal Server errors` are usually problems on the opencti backend. Are there any error logs visible in the opencti platform logs?

Regards

**Comment by nor3th** [comment]
Closed due to inactivity
