### ISSUE TITLE
No "other_stix_ids" defined on an indicator of type YARA when created with pycti

### ISSUE THREAD

**Issue by RomainGUIGNARD** [OpenCTI-Platform/client-python#233]
## Description

When creating an indicator of type 'YARA' by using the pycti client, no 'other_stix_ids' are set on the result indicator in the platform.

## Environment

OpenCTI version: 5.1.3
pycti version : 5.1.3

## Reproducible Steps

Create an indicator of type YARA with the pycti function 'indicator.create' and define an 'id' property on it.

## Additional information

This prevent the correct update of YARA rule content

**Comment by nor3th** [comment]
Hey @RomainGUIGNARD 

You mean you tried creating an indicator using `api_client.indicator.create(id=<your_id>, ...)` ?
Try using settings the `stix_id` value, as `id` isn't a property being used here https://github.com/OpenCTI-Platform/client-python/blob/master/pycti/entities/opencti_indicator.py#L318-L344

Regards

**Comment by RomainGUIGNARD** [comment]
Oh my bad, I hadn't noticed that I wasn't using the correct property.
Thanks a lot @nor3th 
.

Regards
