### ISSUE TITLE
Cannot create reports

### ISSUE THREAD

**Issue by TechBurn0ut** [OpenCTI-Platform/client-python#234]
## Description

Reports do not get created when using the pycti client.   The report can be seen in the Data/Entities stream in the UI, however they do not appear on Analysis dashboard with the rest f the reports.

## Environment

1. OS Amazon Linux AMI 2
2. OpenCTI version: 5.1.2
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a report using the pycti client:

opencti_api_client.report.create(name="Test", description="test report from soar", report_class="threat-report", published="2021-01-06T00:00:00.000Z")

2. Login to the web console, and navigate to the Data/Entities to observe the report.
3. Navigate to the Analysis Dashboard and observe that the report in question is missing.
4. Modify the properties of the report entity (i.e. Mark definitions, author, etc.)
5. Navigate to the Analysis Dashboard and observe that the report in question is missing.

## Expected Output

I expected to see the report in some capacity in the Analysis dashboard.

## Actual Output

Report was created, however does not show up in the Analysis dashboard.
 
## Additional information

![Screen Shot 2022-01-07 at 8 25 28 AM](https://user-images.githubusercontent.com/30411037/148560017-3d4c0074-c798-47b1-82ac-43751ce43ce5.png)
![Screen Shot 2022-01-07 at 8 12 35 AM](https://user-images.githubusercontent.com/30411037/148560057-00c13377-667c-4d1d-80e7-c5736eb15eee.png)

**Comment by nor3th** [comment]
Hey @TechBurn0ut 

Try using the search function for the report `Test123`, I am sure it is somewhere there, maybe the creation date is null...

Regards

**Comment by nor3th** [comment]
Closed due to inactivity.
