### ISSUE TITLE
Implement mapping all identifiers on NetworkTraffic observables in `pycti`

### ISSUE THREAD

**Issue by eliataylor** [OpenCTI-Platform/client-python#241]
## Use case

Implement relationship fields on NetworkTraffic observables according to Stix2.1 schema: https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_rgnc3w40xy

This would add:

`src_ref ` > ipv4-addr, ipv6-addr, mac-addr, domain-name
`dst_ref ` > ipv4-addr, ipv6-addr, mac-addr, domain-name
`src_payload_ref ` > artifact
`dst_payload_ref ` > artifact
`encapsulates_refs ` > NetworkTraffic
`encapsulated_by_ref ` > NetworkTraffic

## Current Workaround

None seem acceptable to me, but in theory:
A. Create SDOs atop the Observables and relate them via `stix_core_relationship`.
B. Use the `stix2` [Creating-Cyber-Observable-References](https://stix2.readthedocs.io/en/latest/guide/creating.html#Creating-Cyber-Observable-References) and submit a Bundle to OpenCTI hoping it get's consumed correctly?
C. When "Linking Observables" in the interface a `StixCyberObservableRelationship` is created with a "src" relationship_type. This doesn't seem to follow the Stix2 defintiion, but works in terms of showing the relationship. Eitherway, I need to create a relationship within our connector not using the interface.

![Screen Shot 2021-12-21 at 1 03 16 PM](https://user-images.githubusercontent.com/6335974/146984548-3241c815-a234-40c0-ae10-a2950bcc7852.png)

## Proposed Solution

Expand the input: https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/config/schema/opencti.graphql#L6740

## Additional Information

https://github.com/OpenCTI-Platform/client-python/issues/231

## If the feature request is approved, would you be willing to submit a PR?

Yes, but probably don't know enough GraphQL yet to take this on quickly. (assuming this would require changes to the query itself?)

**Comment by SamuelHassine** [comment]
Hello @eliataylor @nor3th,

This issue is linked to #155.

**Comment by nor3th** [comment]
The relationships have been introduced, only import/export via STIX isn't functional yet
