### ISSUE TITLE
Allow to fetch data without asking for S3 files

### ISSUE THREAD

**Issue by TechBurn0ut** [OpenCTI-Platform/client-python#245]
## Problem to Solve

When using the python client and querying the API, by default pycti is searching MinIO/S3 for associated files.  While this works for a small data sets, it can causes rate limiting errors in AWS S3 and potential system performance issues with MinIO.

## Current Workaround

None

## Proposed Solution

introduce some options in the lib to allow to fetch data without asking for S3 files

## Additional Information

Using the MinIO Client as an AWS S3 client with opencti

**Comment by SamuelHassine** [comment]
Hello @TechBurn0ut,

For the moment this is not possible to remove importFiles from default queries attributes. But you can use "customAttributes" properties to request only the attributes you need instead of the default ones. So it will not query the files.

Kind regards,
Samuel
