### ISSUE TITLE
Get observables by id  or another method

### ISSUE THREAD

**Issue by mariodcosta** [OpenCTI-Platform/client-python#246]
Hello guys,

I am using OpenCTI platform for my master thesis, and I am exploring the available classes , however I didn't find if it's possible to get an observable by ID or something similar.

I am coding in python language and I am developing a connector to communicate with openCTI platform. 

Thank you very much for your attention.

**Comment by nor3th** [comment]
Hey @mariodcosta 

This should do the job:
```
observable = opencti_api_client.stix_cyber_observable.create(
    simple_observable_key="File.name", simple_observable_value="activeds.dll"
)
observable_get = opencti_api_client.stix_cyber_observable.read(
    id=observable['id']
```

Also have a look at the other examples https://github.com/OpenCTI-Platform/client-python/tree/master/examples

Regards

**Comment by mariodcosta** [comment]
@nor3th i will test your solution, but before I am having a problem connecting my container to the container of the OpenCTI can you take a look in this link [](https://stackoverflow.com/questions/71561336/connect-two-containers-through-docker-network/71563073?noredirect=1#comment126490753_71563073) and give an opinion about my problem?

**Comment by nor3th** [comment]
Hey

Looks more like a docker networking issue to me. Try the example approach https://stackoverflow.com/a/71563073 to check if the docker networking setup actually works or if it is a docker networking issue itself and nothing opencti related.

Regards

**Comment by mariodcosta** [comment]
Your solution worked fine @nor3th . However, for my purpose I am using this function `def list(self, **kwargs)` from this module [](https://github.com/OpenCTI-Platform/client-python/blob/master/pycti/entities/opencti_stix_cyber_observable.py) **line 332**. However, now I am trying to get all observables, because according with that code only return 100 observables (line 334 and 335), and I want all of them, furthermore the total number is variable, so is not so easy like put the code equal to a number. Do you have any idea ?

Thank you very much.

**Comment by nor3th** [comment]
Pagination https://github.com/OpenCTI-Platform/client-python/blob/master/examples/get_all_reports_using_pagination.py#L20-L34 :wink:

**Comment by mariodcosta** [comment]
@nor3th thank you for your reply. But I found a easy way using `def list(self, **kwargs)` , the solution is only invoke the function as attribute define getAll = True, like this `list( getAll = True )`.

Thank you.
