### ISSUE TITLE
'List' method options filter on indicators greater than a specific date or a certain tag

### ISSUE THREAD

**Issue by AAAbou** [OpenCTI-Platform/client-python#258]
## pycti Indicator method 'List'

More information about the 'filter' options inside the 'list' method. 
![image](https://user-images.githubusercontent.com/30905852/172560643-808d6e52-7407-47bc-8501-099d5c059ddc.png)

I'm trying to get from opencti via pycti a list of indicators within a set period of time (last 24 hrs for example)

![image](https://user-images.githubusercontent.com/30905852/172560530-26cd00e9-a805-4e2e-a67a-685d4e5111fa.png)

![image](https://user-images.githubusercontent.com/30905852/172571137-58593718-1978-4b5b-be62-86cbab5f2e53.png)

**Comment by AAAbou** [comment]
Question still the above, But another is what kind of filters can I use/apply on it.

**Comment by daemitus** [comment]
indicator filters: https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/config/schema/opencti.graphql#L3624

**Comment by AAAbou** [comment]
@daemitus Thank you!
