### ISSUE TITLE
KeyError occurs when uploading STIX Object which includes Email-Message Observable with date property

### ISSUE THREAD

**Issue by kohsawa** [OpenCTI-Platform/client-python#266]
## Description
I ran a program to submit a simple STIX Bundle Object to OpenCTI, as shown below.  
And encountered a `KeyError` due to Email-Message not having a property called `attribute_date` when using the version 5.3.7.

* source code
```python
from datetime import datetime
from pycti import OpenCTIApiClient
import stix2

email_message = stix2.v21.observables.EmailMessage(subject="test", date=datetime(2022, 1, 1), is_multipart=False)
report = stix2.v21.sdo.Report(name="test", published=datetime.now(), object_refs=[email_message.id])
bundle_json = stix2.serialization.serialize(stix2.v21.bundle.Bundle([report, email_message]))

opencti_api_client = OpenCTIApiClient("http://localhost:8080", <My access token>)
opencti_api_client.stix2.import_bundle_from_json(json_data=bundle_json)
```

* error message
```
Traceback (most recent call last):
  File "/home/k-ohsawa/study/opencti/test_email_message/mail.py", line 10, in <module>
    opencti_api_client.stix2.import_bundle_from_json(json_data=bundle_json)
  File "/home/k-ohsawa/study/opencti/test_email_message/.venv/lib/python3.9/site-packages/pycti/utils/opencti_stix2.py", line 206, in import_bundle_from_json
    return self.import_bundle(
  File "/home/k-ohsawa/study/opencti/test_email_message/.venv/lib/python3.9/site-packages/pycti/utils/opencti_stix2.py", line 1848, in import_bundle
    self.import_observable(item, update, types)
  File "/home/k-ohsawa/study/opencti/test_email_message/.venv/lib/python3.9/site-packages/pycti/utils/opencti_stix2.py", line 763, in import_observable
    stix_observable_result = self.opencti.stix_cyber_observable.create(
  File "/home/k-ohsawa/study/opencti/test_email_message/.venv/lib/python3.9/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 751, in create
    "attribute_date": observable_data["attribute_date"]
KeyError: 'attribute_date'
```

In fact, I had sent a Pull Request for this issue about a month ago, but that request was not accepted. 
> https://github.com/OpenCTI-Platform/client-python/pull/260

So I'm writing this Issue with a detailed explanation.

Looking at where the problem occurred, the latest tag (5.3.7) and the master branch show the following, respectively.
* 5.3.7 (https://github.com/OpenCTI-Platform/client-python/blob/5.3.7/pycti/entities/opencti_stix_cyber_observable.py#L751-L753)
```python
                    "attribute_date": observable_data["attribute_date"]
                    if "date" in observable_data
                    else None,
```

* master branch (https://github.com/OpenCTI-Platform/client-python/blob/master/pycti/entities/opencti_stix_cyber_observable.py#L751-L753)
```python
                    "attribute_date": observable_data["attribute_date"]
                    if "attribute_date" in observable_data
                    else None,
```

Both of the source code blocks above are where the input STIX Object is converted to match the OpenCTI schema, where observable_data is the input value.

Now, the error message indicates that `Email-Message` does not have a property called `attribute_date`.  
So, looking at the official STIX information, there is no property called `attribute_date`, but instead a `date` property, so of course `observable_data["attribute_date"]` will occur KeyError.
> https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_grboc7sq5514

Also, the source code of master branch is `if "attribute_date" in observable_data`, in which case the if statement is always **NOT TAKEN** and the `date` property will be never sent to OpenCTI.
I can show it in the Actual Output section.

However, OpenCTI uses the `attribute_date` property instead of the `date` property.  
Therefore, the source code block in this problem needs to rename the `date` (Official STIX property) to `attribute_date` (OpenCTI specific one) to meet the OpenCTI schema.

Based on the above, if you look at the changes in the Pull Request I sent earlier, it should solve this issue simply as follows.
```python
                    "attribute_date": observable_data["date"]
                    if "date" in observable_data
                    else None,
```

If my understands are wrong, could you tell me what?

## Expected Output
* the `date` property is showen in each Observables view.
![image](https://user-images.githubusercontent.com/46516325/184342303-68fe940b-881b-425f-a5a4-6ae3a63159e5.png)

## Actual Output
* 5.3.7 tag
  * KeyError is occured like showen the top of this issue.

* master branch
  * `date` property is not showen in each Observables view.
![image](https://user-images.githubusercontent.com/46516325/184341942-82912739-6685-4af6-94da-b659b2015f85.png)

**Comment by nor3th** [comment]
Hey @kohsawa 

Thank you for the stack trace as well as the code snippet. This helped me understand the issue you are facing better than before. After getting your point and the actual issue, I will merge your PR.

Thanks for bringing the issue up again and arguing for your case.

Regards
