### ISSUE TITLE
How can I add a tag to an indicator created from the attribute x_opencti_create_indicator =True

### ISSUE THREAD

**Issue by RegturH** [OpenCTI-Platform/client-python#291]
Currently using : 
`observable = opencti_api_client.stix_cyber_observable.create(
        observableData={
            "type": "Bank-Account",
            "objectLabel" : label["id"],
            "bic": bic,
            "account_number": account_number,
            "iban": iban,
            "x_opencti_description": "A malicious IBAN",
            "update": True,
            "x_opencti_create_indicator" : True
        } 
    )
`

this creates an observable with label and an Indicator without label. Is there any way to add attributes to the created Indicator?

Current Workaround: 
`
iban="55555"
bic="5555"
account_number="4444"
bank_pattern = "[bank-account:iban = '"+iban+"']"
observable_type = "Bank-Account"

    process = opencti_api_client.indicator.create(
        name= iban,
        pattern=bank_pattern,
        pattern_type="stix",
        x_opencti_main_observable_type=observable_type,
        x_opencti_score = 50,
        objectLabel = label["id"],
        #x_opencti_create_observables=True,
        update = True
    )

observable = opencti_api_client.stix_cyber_observable.create(
        observableData={
            "type": "Bank-Account",
            "bic": bic,
            "account_number": account_number,
            "iban": iban,
            "x_opencti_description": "A malicious IBAN",
            "update": True,
        }
        
    )
    author = opencti_api_client.identity.create(
        name="script",
        description="Automated Toolkit",
        type="Organization",
    )
    opencti_api_client.stix_core_relationship.create(
        toId=observable["id"],
        fromId=process["id"],
        confidence=90,
        createdBy=author["id"],
        relationship_type="related-to",
        description="Relation between the indicator/observable objects",
    )
opencti_api_client.stix_cyber_observable.add_label(id=observable["id"], label_id=label["id"])`

This is working but very complicated. Can someone help or explain the x_opencti_create_observables/x_opencti_create_indicator?

@SamuelHassine

**Comment by SamuelHassine** [comment]
Hello,

This has been fixed and is now native.

Kind regards,
Samuel
