### ISSUE TITLE
pycti version 5.4.0 throwing: Unknown argument "objectOrganization" on field "Mutation.stixCyberObservableAdd

### ISSUE THREAD

**Issue by hb-cl** [OpenCTI-Platform/client-python#296]
## Description

Running Example script from [example script](https://github.com/OpenCTI-Platform/client-python/blob/master/examples/add_label_to_observable.py). Getting error while creating an observable. 

## Environment

1. OS (where OpenCTI server runs):  Ubuntu 20 (focal) 
2. OpenCTI version: 5.3.17
3. Other environment details:
None
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.  pip install pycti (I got version 5.4.0)
2.  Download example python script which is creating observable 
3.  run it 

## Expected Output

Observable gets Created or some fail message 

## Actual Output

 {'type': 'url', 'value': 'http://johndoe.com'}
INFO:root:Creating Stix-Cyber-Observable {Url} with indicator at False.
ERROR:root:Unknown argument "objectOrganization" on field "Mutation.stixCyberObservableAdd".
{'name': 'Unknown argument "objectOrganization" on field "Mutation.stixCyberObservableAdd".', 'message': 'Unknown argument "objectOrganization" on field "Mutation.stixCyberObservableAdd".'}
INFO:root:Creating Stix-Cyber-Observable {Url} with indicator at False.
ERROR:root:Unknown argument "objectOrganization" on field "Mutation.stixCyberObservableAdd".
Traceback (most recent call last):
  File "[REDACTED]/test.py", line 47, in <module>
    url = opencti_api_client.stix_cyber_observable.create(
  File "[REDACTED]/venv/lib/python3.10/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1163, in create
    result = self.opencti.query(query, input_variables)
  File "[REDACTED]/venv/lib/python3.10/site-packages/pycti/api/opencti_api_client.py", line 328, in query
    raise ValueError(
ValueError: {'name': 'Unknown argument "objectOrganization" on field "Mutation.stixCyberObservableAdd".', 'message': 'Unknown argument "objectOrganization" on field "Mutation.stixCyberObservableAdd".'} 

## Additional information

 When reverted to pycti version 5.3.17 code works fine

**Comment by SamuelHassine** [comment]
Please be sure to align platform and client versions.
