### ISSUE TITLE
[PyCTI / Front] Add repromote_to_indicator

### ISSUE THREAD

**Issue by MaxwellDPS** [OpenCTI-Platform/client-python#321]
## Problem to Solve

Say an SCO is created with no metadata; Then the `self.octi.stix_cyber_observable.promote_to_indicator(id=sco_id)` can be called, and it passes any metadata the SCO has ie labels description.

But say I add a label to the parent SCO, if I call `promote_to_indicator()` again it does nothing and the new metadata is not reflected on the child indicator

## Current Workaround

The old child indicator must be deleted, then re-created

## Proposed Solution

Add a `repromote_to_indicator()` to abstract this

**Comment by Jipegien** [comment]
I have tested your case through the UI and it seems working fine. Adding a label to a SCO already promoted as an Indicator add the label to the Indicator.

Can you check again? It may have been fixed in a recent version.

**Comment by SamuelHassine** [comment]
Confirmed. It will be fixed soon

**Comment by SamuelHassine** [comment]
Confirmed fix in 5.11.
