### ISSUE TITLE
Cannot add objects to Cases

### ISSUE THREAD

**Issue by TechBurn0ut** [OpenCTI-Platform/client-python#346]
## Description

When trying to add STIX objects to a Case via pycti, I get the following error:

`{'name': 'Cannot query field "caseEdit" on type "Mutation". Did you mean "caseAdd", "cityEdit", "labelEdit", "meEdit", or "noteEdit"?', 'message': 'Cannot query field "caseEdit" on type "Mutation". Did you mean "caseAdd", "cityEdit", "labelEdit", "meEdit", or "noteEdit"?'}`

## Environment

1. OS (where OpenCTI server runs): AWS ECS Fargate - Amazon Linux
2. OpenCTI version: 5.6.2
3. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create Incident Object
2. Create Case Object
3. add incident to case:

`client.case.add_stix_object_or_stix_relationship(id="<ID of Case Object>", stixObjectOrStixRelationshipId="<STIX ID to be Added>")`

## Expected Output

Incident Object added to Case

## Actual Output

Error output

**Comment by richard-julien** [comment]
Will be handle by https://github.com/OpenCTI-Platform/client-python/issues/342
