### ISSUE TITLE
pycti.api error when Creating an Identity. 

### ISSUE THREAD

**Issue by cmandich** [OpenCTI-Platform/client-python#474]
## Description

When using the `create` function to create an `identity`, it raises a `ValueError` in pycti version `5.11.0`. This error does not occur when using pycti `5.10.3`

## Environment

1. Apple Macboo Pro, M1 Pro, Ventura
3. OpenCTI version: 5.11.0
4. Other environment details: Error occurs when in the `external-import/thehive`

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Apply config.yml with valid configuration.
2. Run `python3 thehive.py` 
3. Error will return immediately upon initialization of the class `TheHive`. 

## Expected Output

Should create an `Identity`.

## Actual Output

```
ValueError: {'name': 'Variable "$input" got invalid value { stix_id: null, createdBy: null, objectMarking: null, objectLabel: null, externalReferences: null, revoked: null, confidence: null, lang: null, created: null, modified: null, name: "Rivian", description: "Rivian", contact_information: null, roles: null, x_opencti_aliases: null, x_opencti_stix_ids: null, x_opencti_workflow_id: null, update: false, x_opencti_organization_type: null, x_opencti_reliability: null }; Field "x_opencti_workflow_id" is not defined by type "OrganizationAddInput". Did you mean "x_opencti_stix_ids"?', 'message': 'Variable "$input" got invalid value { stix_id: null, createdBy: null, objectMarking: null, objectLabel: null, externalReferences: null, revoked: null, confidence: null, lang: null, created: null, modified: null, name: "Rivian", description: "Rivian", contact_information: null, roles: null, x_opencti_aliases: null, x_opencti_stix_ids: null, x_opencti_workflow_id: null, update: false, x_opencti_organization_type: null, x_opencti_reliability: null }; Field "x_opencti_workflow_id" is not defined by type "OrganizationAddInput". Did you mean "x_opencti_stix_ids"?'}
```
## Additional information

Error occurs in `thehive.py` with this code. When the code is commented out the code runs as expected. 
```
self.identity = self.helper.api.identity.create(
    type="Organization",
    name=self.thehive_organization_name,
    description=self.thehive_organization_name,
)
```

Tested with `5.10.3` and do not receive the same error.

**Comment by richard-julien** [comment]
Can you double check that python/connectors and platform are all running the same version? thanks

**Comment by cmandich** [comment]
Disregard, I missed the `5.11.1` release, this appears to fix the issue.
