### ISSUE TITLE
Create a full documentation

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/client-python#5]
## Problem to Solve

Currently, there is no documentation on the Python client. It could be useful :)

## Current Workaround

None.

## Proposed Solution

Write the documentation, with examples and methods reference.

## Additional Information

None.

**Comment by 2xyo** [comment]
Maybe you could add the following samples to show how to use `import.py` : 
- https://oasis-open.github.io/cti-documentation/examples/example_json/apt1.json
- https://oasis-open.github.io/cti-documentation/examples/example_json/poisonivy.json
- https://gist.githubusercontent.com/rjsmitre/79775df68b0d1c7c0985b4fe7f115586/raw/d5d2a3e7b4ae52ff7153a8b7b5b57dd066611803/imddos.json 

from https://oasis-open.github.io/cti-documentation/stix/examples#stix-20-threat-reports
