### ISSUE TITLE
ValueError: {'name': 'Unknown type "FilterGroup". Did you mean "FilterMode"?'}

### ISSUE THREAD

**Issue by 0c34** [OpenCTI-Platform/client-python#508]
## Description
Hi I got this error while connecting to opencti api.
ValueError: {'name': 'Unknown type "FilterGroup". Did you mean "FilterMode"?', 'message': 'Unknown type "FilterGroup". Did you mean "FilterMode"?'}

## Code
from pycti import OpenCTIApiClient

api_url = ""
api_token = ""

opencti_api_client = OpenCTIApiClient(api_url, api_token)

malwares = opencti_api_client.malware.list(search="windows")

print(malwares)

**Comment by ezagala** [comment]
Seeing this, as well. It seems like [this](https://github.com/OpenCTI-Platform/client-python/commit/c99eea915c93d005bd963d3533903d7574ce0f8a) commit in version `5.12.0` introduces the regression.

Line 191 includes a call to query `ThreatActors` where the `$filter` parameter is passed an argument of the new type `FilterGroup.` Per the schema this parameter is still expecting an argument of type `FilterMode.` 

This query is executed during in the `heath_check` method that runs when the client is initiated. It blows up the connection and results in the error @0c34 listed above. 

Downgrading to version `5.11.14` has resolves the error, at least until the team can push a fix.

**Comment by 0c34** [comment]
Hi @ezagala 
I have opencti api version 5.11.14 installed it fixed the error.
Thank you.
