### ISSUE TITLE
Use "Type Hints" - PEP 484

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/client-python#54]
## Problem to Solve

It's hard for developers to understand what exactly is going on in code they haven't written and for type checking tools found in many IDEs that are limited due to the fact that they don't have any indicator.

## Proposed Solution

1.  Use type hints ([PEP 484](https://www.python.org/dev/peps/pep-0484/)).
2.  Add [mypy](http://mypy-lang.org/) check to CI.

### Why Type Hints?

* **Helps Type Checkers**: By hinting at what type you want the object to be the type checker can easily detect if, for instance, you're passing an object with a type that isn't expected.
* **Helps with documentation**: A third person viewing your code will know what is expected where, ergo, how to use it without getting them `TypeErrors`.
* **Helps IDEs develop more accurate and robust tools**: Development Environments will be better suited at suggesting appropriate methods when know what type your object is. You have probably experienced this with some IDE at some point, hitting the `.` and having methods/attributes pop up which aren't defined for an object.

### Examples 

From https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#functions

```py
from typing import Callable, Iterator, Union, Optional, List

# This is how you annotate a function definition
def stringify(num: int) -> str:
    return str(num)

# You can of course split a function annotation over multiple lines
def send_email(address: Union[str, List[str]],
               sender: str,
               cc: Optional[List[str]],
               bcc: Optional[List[str]],
               subject='',
               body: Optional[List[str]] = None
               ) -> bool:
```

## Additional Information

* https://www.python.org/dev/peps/pep-0484/ - Type Hints
  * https://www.youtube.com/watch?v=2wDvzy6Hgxg  - Type Hints - Guido van Rossum - PyCon 2015 
* https://docs.python.org/3/library/typing.html
* https://mypy.readthedocs.io/en/stable/index.html 
  * https://mypy.readthedocs.io/en/stable/existing_code.html#using-mypy-with-an-existing-codebase " how to get started using mypy with an existing, significant codebase that has little or no type annotations"  
* https://stackoverflow.com/a/32558710 - What are type hints in Python 3.5?

**Comment by rhaist** [comment]
This is very helpful indeed. A big downside of Python seems to be a missing type hint for JSON.
While working on the docstrings I added type hints for every function that was obvious.

**Comment by 2xyo** [comment]
"JSON type" is long overdue ... See https://github.com/python/typing/issues/182

**Comment by SamuelHassine** [comment]
@2xyo this request is legitimate and pretty useful, but we definitely need help to implement it. Can you provide us with some examples in a quick PR?

Thanks!

**Comment by 2xyo** [comment]
I wait for #89 in order to check that I am not breaking everything :)

**Comment by 2xyo** [comment]
I wait for #89 in order to check that I am not breaking everything :)

**Comment by 2xyo** [comment]
I wait for #89 in order to check that I am not breaking everything :)

I'll try to find some time to do at least one entity like [Intrusion Set.](https://github.com/OpenCTI-Platform/client-python/blob/master/pycti/entities/opencti_intrusion_set.py)

But in order to make it truly compatible with mypy and really useful, it will be necessary to rewrite most of the function definitions as `**kwargs` is everywhere even when we know how many arguments a function should receive (See [Stop Abusing *args and **kwargs in Python](https://medium.com/better-programming/stop-abusing-args-and-kwargs-in-python-560ce6645e14)  :grin:)

Example: https://github.com/OpenCTI-Platform/client-python/blob/d5b3ac1f5f3fa72d83ce64b5ff9046eeebca6d7e/pycti/entities/opencti_intrusion_set.py#L218 

Without rewrite function defintions: no interest! 
```py
from typing import Any

    def create(self, **kwargs: Any) -> Any:
    	stix_id = kwargs.get("stix_id", None)
    	name = kwargs.get("name", None)
    	description = kwargs.get("description", "")
    	update = kwargs.get("update", False)

    	...

```


With rewrite function defintions: it's much easier for developers to use `create()` :)

```py
from typing import Any, Dict, Optional

    def create(self, 
		       namee:str,
		       description: Optional[str] = "",
		       stix_id: Optional[str] = None, 
		       created_by: Optional[Dict] = None, 
		       update: Optional[bool] = False ) -> Any:

		"""
    	Creates an "Intrusion Set" which is a grouped set of adversarial behaviors and resources with common properties that is believed to be orchestrated by a single organization. 

    	:param stix_id: An identifier to identify this Intrusion Set
    	:param name: A name used to identify this Intrusion Set
    	:param description: A description that provides more details and context about the Intrusion Set, potentially including its purpose and its key characteristics
    	:param created_by: The STIX id property of the identity object that describes the entity that created this this Intrusion Set
    	:param update: Choose to updated an existing Intrusion Set 
    	"""
        created_by = createdBy
        ...

```

**Comment by rhaist** [comment]
I fully support @2xyo 's view and think having proper input variables per function would increase the usability for any developer that is working with the SDK. At the moment I have to look into the source code of every function I have to use to see which *kwargs arguments are accepted, how they need to be namend (camel vs. snake case) and how they impact the function flow overall.

So in addition to having better tests and somewhat typed functions we also gain speed and confidence during development.
Also the documentation will be much easier to automate than what we have at the moment.

As this comes with the cost of:

1. Having to rework every class and member function
2. Having to rework every connector

this is a decisions we should discuss thoroughly with @SamuelHassine and @richard-julien.

**Comment by 2xyo** [comment]
To begin with, a compromise would be to use  [@typing.overload](https://docs.python.org/3.9/library/typing.html#typing.overload )  for type checker only (not at runtime):

```py

from typing import overload

@overload
def create(self, 
		   namee:str,
		   description: Optional[str] = "",
		   stix_id: Optional[str] = None, 
		   created_by: Optional[Dict] = None, 
		   update: Optional[bool] = False ) -> Any:

def create(self, **kwargs) :
    <actual implementation>
```

I have to test to see how it's looks in an IDE like vscode.

**Comment by 2xyo** [comment]
It should work without breaking everything:  https://github.com/2xyo/client-python/blob/typehint_indicator/pycti/entities/opencti_indicator.py#L287-L385

Could you please test it?

**Comment by rhaist** [comment]
Do we really want to expose CamelCase variables? I know that the GraphQL API is using them but I think to make it easier for python SDK users to intuitively use our SDK we should rewrite all functions to strict snake_case variables.

**Comment by 2xyo** [comment]
FYI, I played with the [sgqlc ](https://github.com/profusion/sgqlc) graphql client and code generation. And i'm a little bit disappointed : 

- no autocompletion 
- no PEP 484

```console
$ pip install sgqlc
$ python3 -m sgqlc.introspection -H "Content-Type: application/json" -H "Authorization: Bearer <API TOKEN>"  https://demo.opencti.io/graphql opencti_schema.json
$ sgqlc-codegen schema --docstrings opencti_schema.json opencti_schema.py
```

```py
from sgqlc.endpoint.http import HTTPEndpoint
from sgqlc.operation import Operation
from opencti_schema import opencti_schema as schema

url = 'https://demo.opencti.io/graphql'
headers = {'Authorization': 'Bearer <API TOKEN>'}
endpoint = HTTPEndpoint(url, headers)
op = Operation(schema.Query)  
incidents = op.incidents(first=10)
op.incidents.edges()
op.incidents.page_info()
data = endpoint(op)

repo = (op + data).incidents
for i in repo.edges:
    print(i.node)

```

```
Incident(id=c036a2e1-ff2e-4e72-8f41-152b3d7a214f, standard_id=incident--742bb5d2-49f1-5ef5-9a5a-6df328d98350, entity_type=Incident, parent_types=['Basic-Object', 'Stix-Object', 'Stix-Core-Object', 'Stix-Domain-Object'], x_opencti_stix_ids=[], spec_version=2.1, created_at=2021-05-13 21:30:51.000735+00:00, updated_at=2021-05-13 21:30:51.000735+00:00, to_stix={"first_seen":"2021-05-13T21:30:51.722Z","last_seen":"2021-05-13T21:30:51.722Z","spec_version":"2.1","description":"desc B","created_at":"2021-05-13T21:30:51.735Z","revoked":false,"updated_at":"2021-05-13T21:30:51.735Z","modified":"2021-05-13T21:30:51.735Z","id":"incident--742bb5d2-49f1-5ef5-9a5a-6df328d98350","lang":"en","created":"2021-05-13T21:30:51.735Z","confidence":15,"name":"Test B","sort":["incident--742bb5d2-49f1-5ef5-9a5a-6df328d98350"],"x_opencti_id":"c036a2e1-ff2e-4e72-8f41-152b3d7a214f","type":"incident"}, revoked=False, confidence=15, lang=en, created=2021-05-13 21:30:51.000735+00:00, modified=2021-05-13 21:30:51.000735+00:00, x_opencti_graph_data=None, name=Test B, description=desc B, aliases=None, first_seen=2021-05-13 21:30:51.000722+00:00, last_seen=2021-05-13 21:30:51.000722+00:00, objective=None)
Incident(id=98c84eac-18ee-4c92-97ee-d08191c0e507, standard_id=incident--7f580299-3597-56da-8711-1fdb4c9b29ed, entity_type=Incident, parent_types=['Basic-Object', 'Stix-Object', 'Stix-Core-Object', 'Stix-Domain-Object'], x_opencti_stix_ids=[], spec_version=2.1, created_at=2021-05-13 20:57:52.000482+00:00, updated_at=2021-05-13 20:57:52.000482+00:00, to_stix={"first_seen":"2021-05-13T20:57:52.470Z","last_seen":"2021-05-13T20:57:52.470Z","spec_version":"2.1","description":"the desc","created_at":"2021-05-13T20:57:52.482Z","revoked":false,"updated_at":"2021-05-13T20:57:52.482Z","modified":"2021-05-13T20:57:52.482Z","id":"incident--7f580299-3597-56da-8711-1fdb4c9b29ed","lang":"en","created":"2021-05-13T20:57:52.482Z","confidence":15,"name":"test A","sort":["incident--7f580299-3597-56da-8711-1fdb4c9b29ed"],"x_opencti_id":"98c84eac-18ee-4c92-97ee-d08191c0e507","type":"incident"}, revoked=False, confidence=15, lang=en, created=2021-05-13 20:57:52.000482+00:00, modified=2021-05-13 20:57:52.000482+00:00, x_opencti_graph_data=None, name=test A, description=the desc, aliases=None, first_seen=2021-05-13 20:57:52.000470+00:00, last_seen=2021-05-13 20:57:52.000470+00:00, objective=None)
```

**Comment by rlynch-ironnet** [comment]
I'm willing to take a stab at this. I've already got a bit typed out in various places. 

If we're going to do it right, I'd recommend we make a breaking change and return some pydantic models instead of the current dictionaries. Or in the meantime, just spec out everything with `TypedDict` models. 

We could also cleanup some of these massive `kwargs` methods with either explicit parameters as described above, although having 20+ parameters is its own problem. 
- method with tons of parameters
- method with a pydantic model for model input, and extra args explicitly defined?
  -  i.e. indicator.create(args: IndicatorModel, create_observables: bool, ...)
- a combination of the two using multidispatch to prevent breaking changes?
