### ISSUE TITLE
Add Note directly to stix objects

### ISSUE THREAD

**Issue by sudesh0sudesh** [OpenCTI-Platform/client-python#551]
Please replace every line in curly brackets { like this } with appropriate answers, and remove this line.

## Problem to Solve

It would be great, if we could add a cyber observable or other stix objects directly and using something add_notes function

## Current Workaround

We have to recreate the bundle and have to push the bundle.

## Proposed Solution

It would be great, if we could add a cyber observable or other stix objects directly and using something add_notes function

## Additional Information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by Jipegien** [comment]
Currently, we push for the usage of bundle to keep consistent data and control the ingestion.
