### ISSUE TITLE
List and Search functions do not work for some entities (malware, intrusion_set, ..)

### ISSUE THREAD

**Issue by MalwareCantFly** [OpenCTI-Platform/client-python#552]
## Description

Hi,
Trying to retrieve data using list() and search(), via the Python API does not work for some entities.
Even without any filters, there are no results.
The same GraphQL queries as produced by the Python library, do work in the GraphQL interactive playground.

**Example for a broken enity:**
```
opencti_api_client = OpenCTIApiClient(...)
opencti_api_client.malware.list()
```

**Exmple for a working enity:**
```
opencti_api_client = OpenCTIApiClient(...)
opencti_api_client.tool.list()
```

## Environment

OpenCTI & pycti 5.12.29
Python 3.11.4

## Reproducible Steps

see code examples above.

## Expected Output

A list of malware families.

## Actual Output

An empty list.
<img width="449" alt="image" src="https://github.com/OpenCTI-Platform/client-python/assets/33734448/79982e52-ae4c-47ab-af83-b207016ae8ab">

**Comment by MalwareCantFly** [comment]
Hi,
Please review the below scenario, before closing the issue.

Turns out that is was a permission "misconfiguration".

In my setup, I have two connectors (as users) in the same "Connectors" groups.

The two connectors insert data as two different organization.

So the above "bug" would happen when one connector would try to read data created by another connector.
Not sure this makes sense, as a connector should read existing information and check existing data, to avoid duplication or bad logic.

To solve this, I had to one of the two things:
1. Add "bypass all capabilities" to the roles. which of course is only good for testing.
Only this bypass would make it work, selecting all roles except it, won't change a thing.
2. Add the second organization within each user permissions.

From what I recall this behaviour wasn't there before (half a year ago).
Every connector could read the data created by another connectors.
In current configuration, each connector needs to know all other organizations, before reading their data.

Or is there something that I am missing? :)

Thanks!

**Comment by Jipegien** [comment]
Can you check if you activated Organization segregation in your platform ? (security/Policies -> Platform main organization)

If this mode is not active, connectors should be able to access data created by connectors part of other organizations (all other RBAC options considered equals)

**Comment by MalwareCantFly** [comment]
Hi @Jipegien 

I cannot change this feature (using Community Edition):
<img width="809" alt="image" src="https://github.com/OpenCTI-Platform/client-python/assets/33734448/54aebddc-96cf-443c-99a2-69e406591d13">

I do recall setting this feature before though.
Maybe in some previous version it was availiable in Community Edition, and then disappeared?

Is it possible that this setting is still enabled for me behind the scenes?

Thanks!

**Comment by Jipegien** [comment]
Yes it was CE at the early stages. @Kedae @richard-julien  what do you think of this situation? Is an old CE can have kept the platform organization settings without giving the opportunity to change it after?

**Comment by richard-julien** [comment]
I dont think its related to the EE flag.
Today the behavior is like this.

**IF the platform have a platform organization**
-----------------------------------------------------------------------------
// Data with Empty granted_refs are not visible
// Data with granted_refs users that participate to at least one

**IF platform organization is empty**
-----------------------------------------------------------------------------
// Data with Empty granted_refs are granted to everyone
// Data with granted_refs users that participate to at least one

In both case a data with an explicity sharing will be restricted in term of visibility. This behavior doesnt change since nov 2022.

**Comment by MalwareCantFly** [comment]
thank you @richard-julien, @Jipegien 
I think what happened is that for some reason, all my scripts / connectors inserted explicit sharing (as far as I understand).
The same scripts didn't do that around half a year ago :)

Here is an example, of a report created by AlienVault connector (probably with slight diff from latest version):
![image](https://github.com/OpenCTI-Platform/client-python/assets/33734448/e3d38c51-a113-4bc4-9696-2a5f2a0a4bb4)

How can this explicit sharing be removed, when using the API?

**Comment by MalwareCantFly** [comment]
what I was missing:
I've set a specific organiztion to each user, including connector users.
Apparently this causes auto-sharing with the relative organization, whenever a new object is created.

**Comment by richard-julien** [comment]
Yes @MalwareCantFly , organizations are used to add an extra layer of ACL mainly for restrict and sharing.
When user have an organization the data is auto associated to it and then you have the rules explains in the previous message that are applied. Organizations is really a user sharing concept that make sense when you have multiple organizations inside a same platform that want to share data.

If you're platform is not used by many organizations, i dont think you need to use that feature. Or maybe we miss something in the implementation and the overall usage.

Can you describe a bit more what you expect from user organizations?

**Comment by MalwareCantFly** [comment]
Thanks @richard-julien for the thorough explanation!
It makes sense now.
It was all just a big misuderstanding on my part. Sorry for that.
I just jumped the gun with the extra configurations, "assigning" connector users to "corresponding" organizations, without realizing the permission repercussions.
