### ISSUE TITLE
intrusion_set.list(getAll=True) retrieves up to 500 records only

### ISSUE THREAD

**Issue by alvin2038** [OpenCTI-Platform/client-python#586]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description
The intrusion_set.list() method retrieves up to 500 records only even if the dataset contains more than 500 records.

Getting Intrusion Sets data
intrusion_set.list: get_all=True first=500 with_pagination=False
INFO:pycti.entities:Listing Intrusion-Sets with filters null.
Intrusion Sets: 500

## Environment

1. OS (where OpenCTI server runs): Ubuntu 23.04
2. OpenCTI version: 5.7.6
3. Other environment details: Anaconda 3 (Python 3.11.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Call intrusion_set.list() method

    client = OpenCTIApiClient(api_url, api_token)
    print('Getting Intrusion Sets data')
    intrusion_sets = client.intrusion_set.list(getAll=True)
    print('Intrusion Sets: %d' % len(intrusion_sets))

Result:
    INFO:pycti.entities:Listing Threat-Actors with filters null.
    Getting Intrusion Sets data
    INFO:pycti.entities:Listing Intrusion-Sets with filters null.
    Intrusion Sets: 500  **<= max 500 records returned**

## Expected Output
    INFO:pycti.entities:Listing Threat-Actors with filters null.
    Getting Intrusion Sets data
    INFO:pycti.entities:Listing Intrusion-Sets with filters null.
    INFO:pycti.entities:Listing Intrusion-Sets
    Intrusion Sets: 522  **<= expected count**

## Actual Output
    INFO:pycti.entities:Listing Threat-Actors with filters null.
    Getting Intrusion Sets data
    INFO:pycti.entities:Listing Intrusion-Sets with filters null.
    Intrusion Sets: 500  **<= max 500 records returned**

## Additional information
I compared with the attack_patterns.list() method and noticed that intrusion_set.list() does not seem to retrieve the next set of results correctly. After adapting the code from attack_patterns.list(), intrusion_set.list() now returns the expected results.

Diffs:
```

--- opencti_intrusion_set_ORIGINAL.py
+++ opencti_intrusion_set_FIXED.py
@@ -165,6 +165,8 @@
         if get_all:
             first = 500
 
+        print('intrusion_set.list: get_all=%r first=%r with_pagination=%r' % (get_all, first, with_pagination))
+
         LOGGER.info("Listing Intrusion-Sets with filters %s.", json.dumps(filters))
         query = (
             """
@@ -199,9 +201,33 @@
                 "orderMode": order_mode,
             },
         )
-        return self.opencti.process_multiple(
-            result["data"]["intrusionSets"], with_pagination
-        )
+        if get_all:
+            final_data = []
+            data = self.opencti.process_multiple(result["data"]["intrusionSets"])
+            final_data = final_data + data
+            while result["data"]["intrusionSets"]["pageInfo"]["hasNextPage"]:
+                after = result["data"]["intrusionSets"]["pageInfo"]["endCursor"]
+                LOGGER.info(
+                    "Listing Intrusion-Sets", {"after": after}
+                )
+                result = self.opencti.query(
+                    query,
+                    {
+                        "filters": filters,
+                        "search": search,
+                        "first": first,
+                        "after": after,
+                        "orderBy": order_by,
+                        "orderMode": order_mode,
+                    },
+                )
+                data = self.opencti.process_multiple(result["data"]["intrusionSets"])
+                final_data = final_data + data
+            return final_data
+        else:
+            return self.opencti.process_multiple(
+                result["data"]["intrusionSets"], with_pagination
+            )
 
     """
         Read a Intrusion-Set object
```

**Comment by Jipegien** [comment]
Thanks @alvin2038! Can you make a PR with the modification to ease the review? And can you confirm your are using OpenCTI 6.0 ?

**Comment by alvin2038** [comment]
Apologies @Jipegien. I have just started using github and not familiar with pull requests at this time. Will you be able to assist? As for OpenCTI my organization is still using 5.7.6 as this time.

**Comment by Kedae** [comment]
Hi @alvin2038, we obviously are available to review your code and guide you if needed when you'll have open a PR.

But it would be great if you first get to 6.0 because we have updated and improved a lot of stuff since 5.7.6 and you might not have an issue anymore.
Major version from 5.7.6 to 6.0 have some breaking changes, you must check them before.

**Comment by alvin2038** [comment]
Hi @Kedae. Unfortunately I do not have control over the OpenCTI version used. I hear we may move to 6.0 in the near future. I do feel the issue is in the intrusion_set.list() method as it does not have the code to retrieve subsequent results like attack_patterns.list() has.

Let me read up a bit on the Github flow and try to create the PR.

**Comment by alvin2038** [comment]
HI @Kedae. Apologies. I may have misunderstood that you were referring to OpenCTI version. I just noticed pycti 6.0.7 was released, and will try that out.

**Comment by alvin2038** [comment]
Just tested pycti 5.12.x, 6.0.0 and 6.0.7 and got this error.

```
INFO:api:Health check (platform version)...
Getting Intrusion Sets data
INFO:api:Listing Intrusion-Sets with filters
Traceback (most recent call last):
  File "/data/threat_intel/src/opencti/./test1.py", line 16, in <module>
    intrusion_sets = opencti_api_client.intrusion_set.list(getAll=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kohbl/.conda/envs/test/lib/python3.12/site-packages/pycti/entities/opencti_intrusion_set.py", line 278, in list
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/kohbl/.conda/envs/test/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 348, in query
    raise ValueError(
ValueError: {'name': 'Unknown type "FilterGroup". Did you mean "FilterMode"?', 'message': 'Unknown type "FilterGroup". Did you mean "FilterMode"?'}
```

This seems to be a regression of https://github.com/OpenCTI-Platform/client-python/issues/508 which was fixed in 5.11.14.

Here is my test code:

```
import json
from pycti import OpenCTIApiClient

api_url = ""
api_token = ""

opencti_api_client = OpenCTIApiClient(api_url, api_token)

print('Getting Intrusion Sets data')
intrusion_sets = opencti_api_client.intrusion_set.list(getAll=True)
print('Intrusion Sets: %d' % len(intrusion_sets))
```

Anyway back to the original issue. I tested on 5.11.14 and the fix works there.

**Stock 5.11.14:**
```
INFO:pycti.entities:Listing Threat-Actors with filters null.
Getting Intrusion Sets data
INFO:pycti.entities:Listing Intrusion-Sets with filters null.
Intrusion Sets: 500
```

**5.11.14 with fix:**
```
INFO:pycti.entities:Listing Threat-Actors with filters null.
Getting Intrusion Sets data
INFO:pycti.entities:Listing Intrusion-Sets with filters null.
INFO:pycti.entities:Listing Intrusion-Sets
Intrusion Sets: 532
```

**Comment by Kedae** [comment]
Just to be clear on that : you need to have pycti, OpenCTI and any connector to have the same version (6.0.7) in order to get things working correctly.

**Comment by alvin2038** [comment]
Hi @Kedae, Noted on the requirement to have all on the same version. As I do not have control over the OpenCTI version in my organisation. I will try setting up a private instance of OpenCTI 6.0.7 but in the meantime, will you be able to verify my code and fix on your side?

**Comment by Jipegien** [comment]
Thanks @alvin2038 ! :) Please do a PR and we will review and merge it.

**Comment by alvin2038** [comment]
Hi @Jipegien, not sure if I did the Pull Request correctly because I don't see it in the list of Pull Requests. Appreciate if you can assist with the PR as I am quite new to Github. Thanks.

**Comment by alvin2038** [comment]
@Jipegien @Kedae hopefully it's ok now. I see my PR now.
