### ISSUE TITLE
Errors observed while attempting to retrieve notes for a given SDO ID

### ISSUE THREAD

**Issue by gbikram** [OpenCTI-Platform/client-python#587]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

The `OpenCTIConnectorHelper.api.stix_domain_object.notes` function appears to be resulting in errors, making it difficult to retrieve notes for a given SDO ID.

## Environment

1. OS (where OpenCTI server runs):  Dockerized OpenCTI
2. OpenCTI version: 6.0.7

## Reproducible Steps

Steps to create the smallest reproducible scenario:

```python
from pycti import OpenCTIApiClient

client = OpenCTIApiClient(url=<OPENCTI_URL>, token=<OPENCTI_TOKEN>)

notes = client.stix_domain_object.notes(id='<ID of SDO>')     # This function results  in an error
```

## Expected Output

{ Please describe what you expected to happen. }

The function should return a list of notes attached to the SDO.

## Actual Output

The following `ValueError` is observed:

```
ValueError: {'name': 'Cannot query field "edges" on type "Label".', 'message': 'Cannot query field "edges" on type "Label".'}
```

**Comment by Kedae** [comment]
What you are showing is really weird.

`client.stix_domain_object.notes(id='<ID of SDO>')`
doesn't ask for Labels, you shouldn't get this error.

Can you confirm that your smallest reproducible is actually going in error ?

**Comment by gbikram** [comment]
@Kedae - Thanks for looking into this. I am sharing the output from my iPython session. 

Below, I attempt to pull Note objects attached to an existing report. Please let me know if any other information is needed.

```python
In [2]: from pycti import OpenCTIApiClient

In [3]: client = OpenCTIApiClient(url='http://localhost:8080/opencti', token='68eae25e-f176-41eb-aeab-ba5efbf2849e')
INFO:api:Health check (platform version)...

In [4]: report_id = '11949a07-53bd-4ed8-a67c-951cc6b329f3'

In [5]: client.stix_domain_object.notes(id=report_id)
INFO:api:Getting notes of the Stix-Domain-Object
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 client.stix_domain_object.notes(id=report_id)

File ~/.local/lib/python3.12/site-packages/pycti/entities/opencti_stix_domain_object.py:2063, in StixDomainObject.notes(self, **kwargs)
   1953 self.opencti.app_logger.info(
   1954     "Getting notes of the Stix-Domain-Object", {"id": id}
   1955 )
   1956 query = """
   1957     query StixDomainObject($id: String!) {
   1958         stixDomainObject(id: $id) {
   (...)
   2061     }
   2062  """
-> 2063 result = self.opencti.query(query, {"id": id})
   2064 processed_result = self.opencti.process_multiple_fields(
   2065     result["data"]["stixDomainObject"]
   2066 )
   2067 if processed_result:

File ~/.local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py:351, in OpenCTIApiClient.query(self, query, variables)
    347         raise ValueError(
    348             {"name": error_name, "message": main_error["data"]["reason"]}
    349         )
    350     else:
--> 351         raise ValueError(
    352             {"name": error_name, "message": main_error["message"]}
    353         )
    354 else:
    355     return result

ValueError: {'name': 'Cannot query field "edges" on type "Label".', 'message': 'Cannot query field "edges" on type "Label".'}


```

**Comment by gbikram** [comment]
Looks like I was able to fix the issue by  making a small modification in the `opencti_stix_domain_object.py` file. The query under the `notes` function appears to have an error. The `objectLabel` key should not contain `edges` and `node`.

![image](https://github.com/OpenCTI-Platform/client-python/assets/8872186/73ea3ab6-f26d-4548-a5af-02cf0791dd14)

It should be:

```
objectLabel {
    id
    value
    color
}
```

**Comment by Kedae** [comment]
Yep, it seems like an error, I'll investiguate and come back to you :)
