### ISSUE TITLE
Python 3.7 compability

### ISSUE THREAD

**Issue by MaxwellDPS** [OpenCTI-Platform/client-python#597]
## Description

Please re-add python3.7 compatibility (being held up by prometheus-client?) as one of the leading SIEM platforms only supports 3.7 🤦‍♂️

https://docs.splunk.com/Documentation/SplunkCloud/9.1.2312/Python3Migration/PythonDevelopment#:~:text=x%2C%20Splunk%20Web%20supports%20only,both%20Python%202.7%20and%203.7.

## Environment

1. OS (where OpenCTI server runs): N/A
2. OpenCTI version: `pycti==6.0.7`
3. Other environment details: limited execution env

## Actual Output

```
ERROR: Ignored the following versions that require a different python version: 0.18.0 Requires-Python >=3.8; 0.19.0 Requires-Python >=3.8; 0.20.0 Requires-Python >=3.8; 2.1.0 Requires-Python >=3.8; 2.2.0 Requires-Python >=3.8; 2.2.1 Requires-Python >=3.8; 4.4.2 Requires-Python >=3.9; 4.4.3 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement prometheus-client~=0.20.0 (from pycti) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.16.0, 0.17.0, 0.17.1)
```

## Additional information

N/A

**Comment by MaxwellDPS** [comment]
To fix

Prometheus client has to be removed or downgraded to `0.17.1`
Setuptools client has to be removed or downgraded to `68.0.0`

**Comment by Jipegien** [comment]
prometheus-client>=0.17.1 instead of prometheus-client~=0.20.0
