### ISSUE TITLE
Unable to add Stix domain entities to the report.

### ISSUE THREAD

**Issue by sandhyarhym** [OpenCTI-Platform/client-python#62]
![output](https://user-images.githubusercontent.com/55431400/73354664-42c96080-42bc-11ea-802e-7c611a0f8160.PNG)

## Description

{ We have inserted all the stix entities data and created a report. While we try to add entities to the report we are getting an error }

## Environment

1. OS (where OpenCTI server runs): { Ubuntu 18.04. }
2. OpenCTI version: { e.g. OpenCTI 2.1.2 }
3. Other environment details: Using opencti client i.e PyCTI

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. {Inserted all the stix entities}
2. { Created a report }
3. { While adding stix entities to the report using pyCTI getting an error. }

## Expected Output

{  }

## Actual Output

{ Please describe what actually happened. }
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by SamuelHassine** [comment]
Hello @sandhyarhym, 

Thanks for this bug report, could you please provide the error you get from the PyCTI library?
