### ISSUE TITLE
CVEs not returning as intended

### ISSUE THREAD

**Issue by matr3p** [OpenCTI-Platform/client-python#638]
## Description

I am trying to churn out details about CVEs from vulnerabilities under Arsenal with certain criteria/filters using pycti such as CVEs original creation date 8 May 2024 and with CVSS score of 8 and above and also certain keywords. However, the results seems to be way off than intended.

## Environment

1. Ubuntu 22.04.4
2. OpenCTI &Pycti version: 6.0.10
3. Python version 3.12.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
![image](https://github.com/OpenCTI-Platform/client-python/assets/64389552/520e8ef2-b8d5-479b-8d89-524e36871b11)

## Expected Output

CVEs original creation date 8 May 2024 and with CVSS score of 8 and above and also certain keywords.

## Actual Output

![image](https://github.com/OpenCTI-Platform/client-python/assets/64389552/c22037ea-b935-484b-8f80-63e83cebb94f)

**Comment by Kedae** [comment]
Hi @matr3p ,

Just stepping in. Where did you get those "created_after" attributes ? It does not seems to be the way our vulnerability list function works.

**Comment by nino-filigran** [comment]
@matr3p following up on this issue: I see no replies on this topic: is this still an issue?

**Comment by Jipegien** [comment]
Closing the issue. If there is any news, do not hesitate to reopen it.
