### ISSUE TITLE
OpenCTI Documentation online no Python API doc

### ISSUE THREAD

**Issue by b4b857f6ee** [OpenCTI-Platform/client-python#64]
Hello,

Regarding : https://opencti-platform.github.io/docs/clients/python/overview

There is nothing in User's guide and API reference

Where can i find this information?

Thank you.

**Comment by b4b857f6ee** [comment]
Ok, thank you, i saw this, but i don't really know python. Maybe i'm going to ask one of my colleague to help me about it with your exemple :).

**Comment by SamuelHassine** [comment]
A documentation is now available on https://opencti-client-for-python.readthedocs.io/en/latest/.

**Comment by SamuelHassine** [comment]
A documentation is now available on https://opencti-client-for-python.readthedocs.io/en/latest/.
