### ISSUE TITLE
STIX publish issue on OPENCTI plateform by pycti connector

### ISSUE THREAD

**Issue by xrenou** [OpenCTI-Platform/client-python#681]
Hi

After updating connector we are experiencing troubleshoot in STIX publish

Our opencti plateform version is 5.10.2

Because of OS update and python update, we had to update as well our pycti connector:
- from 5.10.1 (working with 5.10.2 plateform) 
- to version 5.12.29 (not working with STIX publishing)

Error detail : 

{'name': 'Variable "$input" got invalid value { stix_id: "identity--275b9dd9-34f9-4068-aeba-26982abd0a9f", createdBy: null, objectMarking: [], objectLabel: [], externalReferences: [], revoked: null, confidence: null, lang: null, created: "2024-05-16T08:29:27.480516Z", modified: "2024-05-16T08:29:27.480516Z", name: "organisation", description: "Hybrid file analyser", contact_information: null, roles: null, x_opencti_aliases: null, x_opencti_stix_ids: null, x_opencti_workflow_id: null, update: true, x_opencti_organization_type: null, x_opencti_reliability: null }; Field "x_opencti_workflow_id" is not defined by type "OrganizationAddInput". Did you mean "x_opencti_stix_ids"?', 'message': 'Variable "$input" got invalid value { stix_id: "identity--275b9dd9-34f9-4068-aeba-26982abd0a9f", createdBy: null, objectMarking: [], objectLabel: [], externalReferences: [], revoked: null, confidence: null, lang: null, created: "2024-05-16T08:29:27.480516Z", modified: "2024-05-16T08:29:27.480516Z", name: "organisation", description: "Hybrid file analyser", contact_information: null, roles: null, x_opencti_aliases: null, x_opencti_stix_ids: null, x_opencti_workflow_id: null, update: true, x_opencti_organization_type: null, x_opencti_reliability: null }; Field "x_opencti_workflow_id" is not defined by type "OrganizationAddInput". Did you mean "x_opencti_stix_ids"?'}

Is that showing that Connector and Plateform versions must be always be the same ?
I can't find that information in documentation

**Comment by romain-filigran** [comment]
Hey Xavier
It is advisable to align the pycti version with the platform version.

**Comment by xrenou** [comment]
Hey Romain :)
Thanks for your answer.
That is what I thought but this retro-compatibility issue is not really documented and is very inconvenient I must say.
Perhaps I fell on the wrong version gap and I hope things will be made to avoid this in the future ^^

Regards

**Comment by xrenou** [comment]
So little question in the other way:

Is 5.12.29 pycti connector version is compatible with the actual last opencti plateform version ?

**Comment by romain-filigran** [comment]
@xrenou : I'm pretty sure it's not compatible. 
This is a problem that the team is working on to offer backward compatibility in future versions.
