### ISSUE TITLE
Export Attached file in context of full export 

### ISSUE THREAD

**Issue by nino-filigran** [OpenCTI-Platform/client-python#686]
## Use case

In context a full JSON export, create an export of all attached files (at least pdf, encoded in json)

Steps to reproduce: 
- Go in a report that has file attached (for instance a PDF)
- click on Generate an export in full, JSON
- check the export

Expected result: 
- files should be contained in the JSON in base64

Current Output: 
- files are not in the JSON

**Comment by aHenryJard** [comment]
FYI I transfered the issue from opencti project to client-python, since I need it on the PR.
