### ISSUE TITLE
The OpenCTI client generates a urlllib3 warning for each request to OpenCTI made over HTTPS

### ISSUE THREAD

**Issue by seanthegeek** [OpenCTI-Platform/client-python#742]
## Description

The `OpenCTIApiClient` is configured to ignore certificate verification to requests made to OpenCTI over HTTPS, which generates this warning for each request.

> warnings.warn(
/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'opencti.example.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings 

This causes the large Docker container logs for each connector.

To prevent this, consider using `urllib3.disable_warnings()`

**Comment by Archidoit** [comment]
Where did you set the config ssl_verify to false? For which connectors?
