### ISSUE TITLE
Introduce integration tests

### ISSUE THREAD

**Issue by SamuelHassine** [OpenCTI-Platform/client-python#78]
## Problem to Solve

No integration tests are available for testing this library.

## Current Workaround

Test manually :)

## Proposed Solution

Implement a full test coverage of this Python library.

## Additional Information

None.

**Comment by rhaist** [comment]
Started working on this in #89

**Comment by 2xyo** [comment]
FYI,  the working draft of the "STIX 2.1 Interoperability Test Document" is available at: 
-  [STIX 2.1 Interoperability Test Document Part 1 V0.1](https://docs.google.com/document/d/1SabxIhjxfg1RAaBj6grsktBzX_UHFI4C8VYStybi-c0/edit )
- [STIX/TAXII 2.1 Interoperability Test Document Part 2 V0.1](https://docs.google.com/document/d/1_y8pstc26Q511No7Z9Ny-PzEZ0aum_lpAEuq6PvEY0M/edit )

Moreover, the new projet "[STIX Generator Notebook](https://github.com/oasis-open/cti-stix-generator )"  should be watched as it might be useful for testing :)

**Comment by rhaist** [comment]
I just added #150 as the next logical step in this journey.

**Comment by SamuelHassine** [comment]
First implementation is enough for the moment, thanks again @rhaist.
