### ISSUE TITLE
Python API create/read observable errors 

### ISSUE THREAD

**Issue by al-roz** [OpenCTI-Platform/client-python#785]
## Description
When I try to create/read an observable I get an error from graphql about unknown type.

Error on create : ValueError: {'name': 'Unknown type "PersonaAddInput". Did you mean "RegionAddInput", "EventAddInput", "GroupAddInput", "OpinionAddInput", or "ReportAddInput"?', 'error_message': 'Unknown type "PersonaAddInput". Did you mean "RegionAddInput", "EventAddInput", "GroupAddInput", "OpinionAddInput", or "ReportAddInput"?'}

Error on read :  ValueError: {'name': 'Unknown type "Persona".', 'error_message': 'Unknown type "Persona".'}

## Environment

1. OS: Ubuntu 16.4
2. OpenCTI version: OpenCTI platform 6.2.11
3. OpenCTI client: python (last version)

## Reproducible Steps
1. Run scripts

Scritp create example:
```
observableData = {
        "type" : "file",
        "name" : "name",
    }

obs = client.stix_cyber_observable.create(observableData=observableData)
```   

Scritp read example:
```
client.stix_cyber_observable.read(id='url--dec12ffb-5852-5c84-87ca-3b11cf1046bf')
```   

client - pycti.OpenCTIApiClient() object

**Comment by marieflorescontact** [comment]
Hi @al-roz ,
Thinking your client-python or OpenCTI is out of sync with the version you are building/interfacing. PersonaAddInput is a feature added in 6.3.0 forward. You need to have updated you client-python to be the matching version of your OpenCTI deployment or vice versa

**Comment by al-roz** [comment]
@marieflorescontact  Thanks for the reply. After synchronizing pycti and opencti versions the error disappeared.
