### ISSUE TITLE
python method to push pdf to report-specific input folder 

### ISSUE THREAD

**Issue by gunnarklee** [OpenCTI-Platform/client-python#99]
## Problem to Solve
There is no client-python method to programmatically push a local pdf to the report-specific import folder (/var/lib/docker/volumes/opencti_s3data/_data/opencti-bucket/import/report/{UUID})

## Current Workaround

the current solution is to use the GUI to manually upload pdfs to reports. This is not scriptable and limits automated report generation. Programatically moving uploaded pdfs from the global imports folder to the report specific folder corrupts the openCTI report.

## Proposed Solution

There is an existing GQL method that is supposed to upload pdfs to report specific folders. this is found here https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/src/resolvers/stixDomainEntity.js as importPush. Alternatively, there is a working client python method (OpenCTIApiClient.upload_file) that uploads PDFs to the global folder. This might be modified to also push to specific report folders.

## Additional Information

the report.add_file python API method uses importPush but does not appear to add any PDFs to the report, it is not clear to me if the importPush method is working as intended.  This closed issue (github.com/OpenCTI-Platform/opencti/issues/44) Suggests that there is an upload method to specific reports but could not find it. perhaps this is referring to the GUI based method.

**Comment by SamuelHassine** [comment]
Hello,

The API is already implemented using `stix_domain_entity.add_file`. You have an example here: https://github.com/OpenCTI-Platform/client-python/blob/master/examples/upload_file_to_intrusion_set.py.

Just pass the report_id instead of the intrusion_set ID.
